- release/major-cockpit-release
- release/release-guide
Clean it up a bit and upload a possible directory index. And fail if documentation doesn't exist.
> release: Update the release-guide script

- example/semaphore-run
- example/testsuite1
- example/testsuite2
This script mounts the test directory inside a running container
as /test and runs the passed command.
> test: Add a semaphore abstraction script

- Makefile
> release: Remove stage image after container

- release/release-srpm
- tests/vm-prep
Use 4-space indentation everywhere.
> Make indentation consistent

- tests/README.md
Long term these should go into ansible scripts or some sort of
helpful confugration. But having them documented is a start.
> tests: Add some notes about what needs config on host machines

- Makefile
- tests/Dockerfile
- tests/README.md
- tests/cockpit-tests
- tests/cockpit-tests.json
- tests/install-service
Also parameterize the place to publish to.
> tests: Use a /cache directory instead of /images

- .gitignore
- example/semaphore-run
- sink/README.md
- sink/sink
- sink/test-logic
- sink/test-sink
- sink/test-sink.conf
This allows the sink to periodically check GitHub to see if state is still as it expects.
> Add support to sink for verifying GitHub expectations

- tests/cockpit-tests
This file produces the possible set of bot tasks to be executed in the
current repository by bots. Empty lines and commented lines are ignored
and commented lines are removed. If this file is executable it will be
run, and the output will be used as the list of tasks.
The tasks are sorted descending alphabetically and a task is chosen from
near the top of the sorted result. The task will be run in a shell by the
Cockpit bots.
Depends on:
> tests: Run or load the .tasks file in the target repository

- tests/cockpit-tests
This needs to be run within the cockpit repository root
directory.
> tests: Execute the .tasks file in right directory

- tests/cockpit-tests
Wait for 60 seconds when no task is available or the last task
failed.
> tests: Wait for 60 seconds when no task is available

- release/release-source
We don't want to miss the changes.
> release: Don't exclude aclocal.m4 from patches

- tests/Dockerfile
We want to be able to use machine learnin from the python sklearn
library in our bots.
> tests: Add sklearn dependency

- base/Dockerfile
- images/Dockerfile
- release/Dockerfile
- tests/Dockerfile
image: apply dockerfile good practices
tests: invoke container in exec form
tests: chain metadata instructions
tests: chain run instructions
tests: don't install present packages
base: chain all run instructions
base: tar, util-linux are in base image
dockerfile: label maintainer > MAINTAINER instr
base: use latest stable Fedora: 26
> Modernize dockerfiles

- release/releasetrigger@.service
This is required to release "welder-web".
> release: Allow dashes in project names for GitHub release trigger

- release/README
This includes a zero version and an empty %changelog.
> release: Document the requirements for a spec file

- release/README.md
Rendered result for easier review: https://github.com/martinpitt/cockpituous/tree/release-docs/release
> release: Document how to test release scripts

- base/Dockerfile
- tests/Dockerfile
> Updates to tests container

- learn/README.md
- learn/train-tests
This adds a well known HTTP REST path to the log of the latest training.
> learn: Well known path to latest log of training

- learn/README.md
- learn/analyze.py
- learn/cluster.py
- learn/train-tests
In addition make the cluster json output have the same format as the statistics.
> learn: Gather statistics for the tests

- Makefile
- tasks/Dockerfile
- tasks/README.md
- tasks/cockpit-tasks-bos.yaml
- tasks/cockpit-tasks-centosci.yaml
- tasks/cockpit-tasks-webhook.yaml
- tasks/github_handler.py
- tasks/webhook
> tasks: Handle pull request events in webhook

- tasks/cockpit-tasks
- tasks/cockpit-tasks-webhook.yaml
@martinpitt  I just took your patch, and added the `work=` on line 116
> tasks: Sleep after main cycle

- learn/test-cluster
These would fail previously due to the way things were
changed in #219 and 144bdafb8c575a92c2b63ffba4908c1fd8107ef1
> learn: Fix the test-cluster unit tests

- tasks/webhook
> tasks: Only pull latest cockpit in webhook when new PR is merged

- release/README.md
- release/release-copr
- tasks/cockpit-tasks-webhook.yaml
- tasks/webhook
See individual commits for details.
> release: sink configuration fixes

- tasks/cockpit-tasks
> tasks: Check for tasks in cockpit-podman

- release/README.md
- tasks/cockpit-tasks
> Rename welder-web to cockpit-composer

- tasks/Dockerfile
cockpit-composer's i18n system still needs that.
> tasks: Put back python

- release/README.md
Also update the obsolete container name.
> release: Document automatic release deployment

- tasks/webhook
> webhook: Pubish payload to queue directly

- tasks/README.md
> webhook: Update documentation concerning the webhook queue

- tasks/Dockerfile
> tasks: Add python styling packages to test cockpit-project/bots

- images/install-service
- tasks/install-service
This will allow us to run our bots in AWS EC2 instances with RHEL 8.
> Adjust tasks and images for podman

- Makefile
- README.md
- example/semaphore-prepare
- example/semaphore-run
- example/testsuite1
- example/testsuite2
- sink/sink
- sink/test-logic
- sink/test-sink
- tasks/doc/inkscape-export.py
- tasks/github_handler.py
- tasks/webhook
The example directory mostly seems to come from some semaphore tutorial.
Instead, move these bits to `make check`. Semaphore config already got
changed to invoke that instead.
> Clean up test invocation, pyflakes/pycodestyle fixes

- Makefile
- sink/sink
- sink/test-sink
> Port sink to Python 3

- tasks/cockpit-tasks
See https://github.com/weldr/lorax/pull/842
> tasks: Run .tasks for weldr/lorax

- tasks/cockpit-tasks-psi.yaml
We've been using this config for quite a while now, even though it was scaled down.
> tasks: PSI task bots

- tasks/install-service
See https://github.com/cockpit-project/bots/pull/691
> tasks: Plumb through email notification variables

- tasks/Dockerfile
- tasks/cockpit-tasks
> tasks: Various cleanups

- tasks/cockpit-tasks-centosci.yaml
- tasks/cockpit-tasks-psi.yaml
- tasks/install-service
Firstly lets see if 5 jobs won't make things too brittle.
> Batches and more jobs

- sink/sink
- sink/test-sink
> sink: Exit 77 on collision

- tasks/webhook
> tasks: Add issue-scan to the webhook setup

- images/README.md
- images/generate-image-certs.sh
This previously only lived on cockpit-9.
> images: Add script to generate image server certificates

- tasks/cockpit-tasks
- tasks/run-local.sh
- tasks/webhook
This will allow us to regression-test a bots PR with run-local.sh.
> tasks: Introduce environment variables for bots repo/branch

- tasks/Dockerfile
> tasks: Add python3-pillow and s3-keys symlink 

- .github/workflows/tests.yml
- ansible/aws/README.md
- images/Dockerfile
- metrics/README.md
- release/Dockerfile
- release/README.md
- release/release-dockerhub
- release/release-runner
- tasks/Dockerfile
- tasks/README.md
- tasks/cockpit-tasks
- tasks/doc/verify-diagram.svg
- tasks/run-local.sh
- tasks/webhook
This is gonna be almost impossible to get right on the first try.  I feel like we should just kick off some container builds, then land this, and pick up the pieces later.
> big rename-to-main PR for cockpituous

- ansible/aws/launch-tasks.yml
- tasks/Dockerfile
- tasks/install-service
We had to start AWS tasks again, some hiccups along the way. This is rolled out, and working now.
> ansible: AWS tasks fixes, fix container build

- tasks/Dockerfile
So that we can generate coverage reports during CI.
> tasks: Add lcov

- tasks/run-local.sh
`image-upload --state` does not currently work with S3 stores, as the
checksum is not part of the file name. We can and should fix this later,
but for now, test what an actual image upload would look like. Fake a
"testimage" for that.
Set up a https://min.io/ S3 container, and use it to test image
uploading and downloading with an S3 store.
---
Need to go via the bots here, as locally this doesn't work for me. The upload fails with code 500, and the images container says
```
[crit] 4#4: *3 open() "/cache/images/0000000002" failed (75: Value too large for defined data type), client: 10.0.2.100, server: cockpit-tasks, request: "PUT /testimage-e258d248fda94c63753607f7c4494ee0fcbe92f1a76bfdac795c9d84101eb317.qcow2 HTTP/1.1", host: "cockpituous:8443"
```
This is something weird between file …
> tasks: Test image upload/download with a fake image instead of --state, and with S3 store

- tasks/Dockerfile
- tasks/cockpit-tasks
> tasks: Drop obsolete secrets links, Drop S3 image pruning

- tasks/Dockerfile
> tasks: Move to Fedora 36

- tasks/install-service
See ansible/{aws,psi}/launch-tasks.yml
> tasks: Set correct number of instances in install-service documentation

- ansible/psi/README.md
- ansible/psi/deploy-all.sh
- ansible/psi/import-coreos.sh
- ansible/psi/launch-tasks.yml
- ansible/psi/psi_defaults.yml
- ansible/roles/launch-openstack-instance/tasks/main.yml
See individual commits for details. I rolled this out, using `deploy-all.sh`.
> Move PSI instances to Fedora CoreOS, add script for mass-deployment

- ansible/maintenance/deploy-tasks-container.yml
This was forgotten in https://github.com/cockpit-project/cockpituous/pull/509
> ansible: Adjust deploy-tasks-container.yml for moving webhook to AWS

- tasks/run-local.sh
minio renamed `mc policy` to `mc anonymous`.
> tasks: mc policy is deprecated

- tasks/Dockerfile
> tasks: add python3-pip and esbuild to the tasks container

- ansible/aws/aws_defaults.yml
- ansible/aws/tasks/launch-coreos.yml
- ansible/roles/nested-kvm/tasks/main.yml
We needed to bring up an EC2 CI runner today. These are the current fixes to make that work again.
> ansible: Fix EC2 CoreOS launching

- local-s3/install-s3-service
- tasks/run-local.sh
Fixes [this failure](https://github.com/cockpit-project/cockpituous/actions/runs/4552907132/jobs/8028831223?pr=545)
> tasks: Update for new minio/mc policy API

- tasks/Containerfile
Anaconda's build system needs that.
---
See https://github.com/cockpit-project/bots/pull/5249
@KKoukiou FYI
> tasks: Install pigz

- .cockpit-ci/run
- tasks/run-local.sh
This reproduces and validates https://github.com/cockpit-project/bots/issues/6042
> tasks: Test directory attachment

- tasks/cockpit-tasks-centosci.yaml
- tasks/install-service
Sorry about that. I rolled this out, and confirmed that statistics processing now works.
> Fix statistics processing in OpenShift tasks

- tasks/container/Containerfile
> Fedora 40, install ruff from distro packages

- tasks/container/Containerfile
Required for: https://github.com/cockpit-project/cockpit/pull/20049
> tasks: container: temporarily add python3-pcp as dependency for tests

- ansible/psi/README.md
- ansible/roles/tasks-systemd/tasks/main.yml
My actual task was investigating how to get back PSI cloud authentication, but that's just broken. I'll file a SNOW ticket about that.
> two small fixes

- ansible/psi/deploy-all.sh
- ansible/psi/psi_defaults.yml
This is semi-deployed: nodes 38-42 are now Fedora 42 the rest is still Fedora 40.
> Fedora 42 upgrade
