cockpit-project/cockpituous

release/major-cockpit-release
It's been a while since we've pushed into Fedora 24. There's no reason to do Fedora 24 releases in Koji any more.
We still do Fedora 24 releases in COPR.
=> release: No longer build Fedora 24 releases in Koji

release/release-srpm
That is, any additional files available in the SOURCE_DIR will be
copied in the working dir of SRPM creation. That allows to copy
files such as gpg keys, or configuration files that are only provided
downstream.
Signed-off-by: Nikos Mavrogiannopoulos <nmav@redhat.com>
=> release-srpm: copy additional files in the srpm dir

release/release-dsc
Add a $RELEASE_PATCHES env var and -P option similar to release-srpm.
When enabled, copy our git  patches to debian/git-patches/. Do not create
a quilt series, as quilt is not able to apply git's binary patches.
Instead, debian/rules will be updated to apply them with git, same way
as in cockpit.spec (https://github.com/cockpit-project/cockpit/pull/6052).
Also fix the documentation comment about -s:  This needs to specify the
path to the "control" file, not the debian directory.
=> release-dsc: Copy patches if requested

release/release-srpm
Make sure all the combinations of how these are specified are
handled.
1. If a directory is specified but no tarball, then find the
tarball in that directory
2. If a tarball is specified but no source directory, then
treat the source directory as empty.
3. If source is specified then load patches from source directory.
=> release-srpm: Fix parsing of source directory vs. tarball

release/release-srpm
Often a tarball will include the spec file. We should support loading
it from there and look for it there first.
=> release-srpm: Load spec file from either tarball or working directory

release/release-srpm
For tarballs that are symlinks to an actual tarball, we resolve
those before trying to perhaps trying to parse a tag from them.
=> release-srpm: Resolve tarball symlinks early

release/release-debian
https://github.com/cockpit-project/cockpit/pull/6055 introduces a
generic "debian/adjust-for-release" script which does the PCP build
dependency mangling. Call this if present instead of hardcoding cockpit
specifics.
Fixes #6055
~~This is blocked on landing https://github.com/cockpit-project/cockpit/pull/6055 first.~~ (landed)
=> release-debian: Drop cockpit specific PCP hack

release/release-source
We need to be able to better diagnose build failures.
=> release: Make release-source more verbose

release/major-cockpit-release
We don't want to push new packages into fedora 25 anymore.
=> release: Build for fedora-26

release/release-github
If there's strange characters in the tag then the posting to
github falls over. So remove them.
=> release: Remove strange characters from Git tags

release/major-cockpit-release
We consider the latest cockpit release on Fedora 25 to be stable.
=> release: Stop pushing Fedora 25 builds into Bodhi

Makefile, base/Dockerfile, release/Dockerfile
We need that plugin to install the cockpit build dependencies.
=> release: Ensure dnf knows builddep

Makefile
This is a path specific to the system cockpituous was written on.
=> Fix the 'make verify-shell' target to not use /opt path

verify/Dockerfile
This makes test/vm-prep work inside of the verify container.
=> verify: Prevent KVM modprobe usage in the verify container

verify/cockpit-verify
We don't want the verify script to prune images automatically.
The image store should decide when and how to call the pruning scripts.
=> verify: Prune less often

Makefile, verify/Dockerfile, verify/README, verify/cockpit-verify, verify/cockpit-verify.service, verify/network-cockpit.xml, verify/vm-prep
This helps things be self-contained, reduces deployment
effort, but also helps us work with socket + mcast qemu networks.
It turns out on RHEL 7 socket + mcast in a container doesn't work
properly if sharing the host network namespace. At least on our
RHEL based verify machines it doesn't.
=> Use an isolated network namespace in verify machines

tests/vm-prep
When run in Kubernetes the Pod can outlast the Container and
so this network may have leaked in from elsewhere. Lets double
check and remove it using brctl.
=> test: Make vm-prep double check that cockpit1 doesn't exist

tests/cockpit-tests
This has side effects with keeping the /build directory
cached properly as well as things like the github rate-limit
caching.
We need to work on caching further later, and this should be
viewed as an interim fix. Perhaps later we will cycle every
100 runs or so.
=> tests: Keep the containers and pods running longer

tests/Dockerfile, tests/README.md
This is a file that may contain non-public URLs of where to
download non-public images.
=> tests: Add 'image-stores' file to the container secrets

Makefile, base/push-container
To avoid copying and pasting code in the Makefile for pushing containers, we move the logic there into a shell script.
=> base: Add a push-container script for reuse

tests/Dockerfile
This allows virt-builder to run without a network bridge or libvirt in place.
=> tests: Use direct libguestfs backend for virt-builder

images/nginx.conf
This resulted in massive slow downs for several users.
https://github.com/cockpit-project/cockpit/issues/6571
=> images: Disable HTTP/2 on the images Web Server

release/major-cockpit-release
We don't regularly release to Fedora 25 any more, so drop koji build.
Stop allowing failures on Fedora 26 as that is now our primary target.
See https://github.com/cockpit-project/cockpit/pull/6602
=> release: Enforce success on Fedora 26, drop Fedora 25

tests/README.md, tests/install-service
This is exactly the same rule that qemu-system-x86 puts in
place when it installs.
=> tests: Document right rule for KVM usage

tests/README.md
As we migrate way from vm-prep on master, this will become less
of an issue. But for now the libvirt bridged network in the container
needs this to be loaded.
=> tests: Add troubleshooting info about ip6_tables

tests/cockpit-tests
Make the sleep while waiting longer, roughly the same order of
magnitude to how long it takes to run a test suite.
And perform less tasks in a batch before cycling the container.
=> tests: Make the sleep while waiting longer

tests/cockpit-tests
The first hack is because we don't want to see this error message
when libvirt tries to write bridge related stuff:
error: Unable to set bridge cockpit1 forward_delay: Read-only file system
Secondly, when run in Kubernetes the Pod can outlast the Container and
so this network may have leaked in from elsewhere. Lets double
check and remove it using brctl.
Neither of these hacks work in the tasks code because it may be
executing older branches which do not account for these things.
=> tests: Add cleanup hacks for container networking

tests/Dockerfile, tests/cockpit-tests, tests/cockpit-tests.json
Add a scratch empty volume to a container for the /tmp directory
and start to do the builds and running of VMs there.
=> tests: Add a volume to container for tmp

tests/Dockerfile, tests/README.md
=> tests: Add Red Hat subscription credentials to testers

release/release-source
In release-source we generate patches for every git commit
after the tag. However some commits don't affect the tarball
and therefore should be skipped and not generate patches
for the tarball.
=> release-source: Don't generate patches for non-tarball commits

release/README, release/release-bodhi
bodhi changed recently to now ask for the Fedora (kinit) passsword, and
the bodhi specific password is not being used any more.  See
https://bugzilla.redhat.com/show_bug.cgi?id=1449045 for details.
Note that this needs the latest python-fedora from updates.
----
The previous 140 release attempt [failed due to this](https://fedorapeople.org/groups/cockpit/logs/release-140/log), and I re-ran the lost steps manually, which finally created a [bodhi update for 140](https://bodhi.fedoraproject.org/updates/cockpit-140-1.fc26). I stopped the release container for the time being, as we need to rebuild it.
=> release-bodhi: Move to fedora password

release/release-copr
Abort release-copr in the "prepare" phase already if ~/.config/copr is
expired. Previously it failed too late in the "commit" phase on an
expired token, breaking the release.
=> release: Check expiration of copr config

release/release-srpm
git's --format='%(taggeremail)' already wraps the address in <>, so
don't do it again when creating the changelog. Drop it from the
changelog building and instead add it to the fallback when releasing a
source from non-git.
Fixes duplicate << >> wrapping in e. g.
http://pkgs.fedoraproject.org/cgit/rpms/cockpit.git/commit/?id=2caac4ddcb
=> release: Fix malformed email addresses in release-sprm

release/release-source
The tarballs of a distributed package contain some random
decisions about dependency versions, configure and aclocal.m4
contants and other sources of variation.
In order for release-source to create small reliable patches
we should preseed our rebuild directory with the tarballs.
This only affects files that are either ignored by git or
are otherwise extra in the repo. Committed files remain
true to git commits and are not seeded from tarballs.
=> release: Make release-source preseed rebuild with tarballs

tests/Dockerfile
This is a prerequisite to the bots doing some fuzzing.
=> Add american-fuzzy-lop to things we want to use while testing

tests/README.md
Unless libvirt is used on the Openshift host, the kvm module
is often not loaded by itself.
=> tests: Document doing modprobe /dev/kvm on boot

tests/Dockerfile
I'd like to consume these logs in talks and discussions about our
setup. These show the number of VMs that were launched, which operating
systems, on which hosts, and for how long they ran.
I would like to gather these for many months without cleaning up the
data.
=> tests: Make the qemu logs persistent

tests/README.md, tests/cockpit-tasks.json, tests/cockpituous-account.json
This enables use of non-privileged containers for running the tests
and bot tasks.
Certain older branches will still need to use privileged containers
because they expect to use a cockpit1 bridged host network. However
those cases can be handled by non-Openshift containers run via the command
$ sudo atomic run cockpit/tests
I'd like to eventually rename the usage of 'tests' to 'tasks' in this
repo. This pull request starts that but doesn't finish it.
=> tests: Start to use non-privileged containers

tests/cockpit-tests
Various tasks have timeouts of their own such as running tests
or building images. But if any task hangs for more than 12 hours
we kill it.
We do want to allow for tasks that take a long time such as
machine learning tasks, but they should be broken up to take
significantly less than half a day.
=> tests: Add 12 hour timeout for any task

release/release-copr
That way we can be sure the rpms will be available to
the docker images.
=> release: Wait for copr build to finish

release/release-debian
Drop the rsync of Debian repo to it, as otherwise release-debian fails
now.
The repository is still available at
https://fedorapeople.org/groups/cockpit/debian/
----
Log from today's failed release: https://fedorapeople.org/groups/cockpit/logs/release-152/log
`release-debian` is the last one in the list, so everything else completed and this wasn't actual fatal.
In the near future the current form of release-debian should stop, as our custom repo is not very relevant any more (nor is Debian 8). On the side I'll work on automating most parts of the release to Debian unstable, then we can replace release-debian with that.
=> release: Red Hat OpenShift 2 cloud is gone

Makefile, base/push-container, release/cockpit-release.service
Fedora and RHEL are now more strict about what the default
registry is. Lets explicitly use docker.io here.
In addition there's a bit of renaming going on
=> Makefile: Fix pushing and tagging of containers

tests/Dockerfile
This allows us to experiment with moving Cockpit tests from PhantomJS to
the Chrome Debugging Protocol, using headless Chromium
(https://github.com/cockpit-project/cockpit/pull/8069)
----
Note that there has not yet been a final decision between Electron and Chromium, but unlike electron it is impractical to pull in Chromium via NPM.  There are no pre-built chromium-headless packages on NPM, and https://www.npmjs.com/package/chromium is the full version which requires X and its libraries (which we don't have in the tests container).
Thus it might be that we revert this again soon, but this unblocks https://github.com/cockpit-project/cockpit/pull/8069
=> tests: Install chromium-headless

tests/cockpit-tasks.json, tests/install-service
Docker containers only get a 64 MB /dev/shm by default, which cannot be
increased through OpenShift [1]. The recommendation is to use volumes
instead, so just use the host's /dev/shm. This will enable us to use
chromium-headless or electron in our tests docker containers, which use
shared memory to exchange data between processes. Some of these, like
HTML dumps or screenshots are rather big, and multiple parallel
processes often exceed the 64 MB limit.
For the standalone cockpit-tests.service, bump the SHM size to 500MB.
[1] https://docs.openshift.com/container-platform/3.6/dev_guide/shared_memory.html
=> tests: Increase SHM size

base/Dockerfile, images/Dockerfile, tests/Dockerfile
Now that Fedora 27 is released, Fedora 25 will be EOL really soon. Update our containers to Fedora 26.
While I was at it, I also optimized the tests container's layering to save half a Gigabyte.
I locally ran a build and test/verify/run-tests successfully.
TODO:
=> Update containers to Fedora 26, optimize layering

images/Dockerfile
Cockpit expects to talk to cockpit-11 on the standard HTTP port [1], and
apparently the created cockpit-tests.service had been manually changed
for that until the reinstall. As we don't need port 80 for anything
else, change the port in the Dockerfile instead of changing REDHAT_PING,
to keep the recent behaviour.
[1] https://github.com/cockpit-project/cockpit/blob/master/bots/tests-scan#L58
=> images: Expose http on standard port 80

release/release-bodhi
That tool changed all its options, and provides no backwards compatibility.
Signed-off-by: Nikos Mavrogiannopoulos <nmav@redhat.com>
=> bodhi: update for F26 bodhi

sink/sink
This code change allows the sink to make arbitrary HTTP requests.
It always code do this, but was all framed within the GitHub
moniker. This is mostly cleanup.
=> sink: The sink can make arbitrary HTTP requests

tests/cockpit-tasks.json
Commit 7506c4 used a bind mount from the host's /dev/shm/ into the
container's /dev/shm to increase shared memory size. This causes SELinux
violations:
avc:  denied  { write } for  pid=59335 comm="Chrome_IOThread" name="/" dev="tmpfs" ino=13316 scontext=system_u:system_r:svirt_lxc_net_t:s0:c2,c8 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir
which break chromium. So define the shm volume as standalone tmpfs
instead.
=> tests: Use separate SHM tmpfs volume

tests/Dockerfile
Current chromium 61 has a bug in `Network.setCookie()` which is hard to
work around and fixed in 62. Install chromium-headless from
updates-testing, which gets current upstream versions much more timely.
=> tests: Install latest chromium-headless from updates-testing

tests/Dockerfile
This blocks https://github.com/cockpit-project/cockpit/pull/8193
=> tests: Include python3 in the tests container

sink/sink
This fixes the following error when using watches:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
=> sink: Fix TypeError in GitHub/HTTP logic

tests/Dockerfile
Headless Chrome does not handle requests for client SSL certificates
(https://bugs.chromium.org/p/chromium/issues/detail?id=757181) and there
is no known workaround. These are issued by OpenShift's OAuth during
Cockpit's container tests. Install the full chrome and Xvfb for the
time being so that we can run the container tests under "full" chrome.
(Other tests can continue to use `--headless`).
=> tests: Install full chromium and Xvfb

images/install-service, release/cockpit-release.service, tests/install-service
Clean up a stale `cockpit-{tests,images,release}` at boot before
starting a new one, to avoid failed units and thus non-running image
containers after an unclean reboot.
---
This often happened on verifymachine4/5 and thus public image servers didn't exist until someone cleaned up manually. I tested and rolled out the changes there.
=> systemd: Avoid container startup failure on stale Docker containers

release/README, release/release-runner
This allows release-runner to work for projects other than cockpit.
release/cockpit-release.service already passes in that repository
through `-r`, so for cockpit this works exactly as before.
=> release: Clone specified repository instead of cockpit

tests/cockpit-tests
This will guarantee that we don't have any built leftovers from previous
runs. This becomes even more important when testing third-party modules.
=> tests: Clean the tree after resetting

release/release-runner
Declare -t option to have an argument, otherwise it fails with
release/release-runner: line 153: OPTARG: unbound variable
=> release-runner: Fix -t option

Makefile, release/README, release/cockpit-release.service, release/releasetrigger.socket, release/releasetrigger@.service
So far cockpit-release.service restarted itself every 30 minutes to
poll if a new release is pending. This is a waste most of the time, and
an annoying delay when a release actually happens.
Make this unit start via a HTTP request instead, so that it becomes
suitable as a GitHub "create" web hook, and generalize the mechanism to
work with more than just cockpit:
Add a releasetrigger.socket that listens on port 8090 and activates
releasetrigger@.service. This receives a HTTP request and uses the
path to select the project (sanitizing it to just alphanumeric
characters). If `<project>-release.service` exists, start that and
report success, otherwise report a 404.
There is no user input aside from the sanitized HTTP path, so at most a
remote can try to DoS. Mitigate this by limiting …
=> release: Replace release polling with GitHub trigger

release/release-copr
copr-cli supports a direct local srpm upload just fine now, so cut out
the upload to fedorapeople.org. This takes out a possible point of
failure and also makes the script usable for other projects.
=> release-copr: Upload srpm to copr directly

Makefile, release/welder-web-release.service
This is fairly similar to cockpit-release.service, but configures the
git repository and cockpituous script path for welder-web.
=> release: Add welder-web-release.service

release/release-srpm
Fill in default information for the %changelog body, author, email and tag date if relevant information wasn't found.
=> release: Always include a changelog body, author and email

release/release-bodhi
These are targetted at the EPEL Fedora repository.
=> release: Allow use of strings like EL7 with the release-bodhi script

images/Dockerfile, images/README.md, images/cockpit-images.yaml, images/images-claim.yaml, images/install-service, images/nginx.conf, tests/cockpit-tasks.json
I rebuilt the container with this changes, rolled it out onto both CentOS CI *and* our existing image stores on verifymachine4/5 (to demonstrate backwards compatibility). The new image store is here: https://images-cockpit.apps.ci.centos.org/
This needs some fixes to Cockpit's image-{upload,download}, in https://github.com/cockpit-project/cockpit/pull/9321 .
=> images: Fix container to work on OpenShift, and add deployment resources

sink/sink
Make sure that all uploaded/attached files are readable once the
sink is done with them. These are published, and should be world
readable.
=> sink: Make all uploaded files readable

tests/Dockerfile, tests/cockpit-tests
In some restricted OpenShift environments pods get started with a random
UID:
- Don't chown files and use sudo, use world-writable directories
instead.
- Explicitly set $HOME, as the random UID does not have a passwd entry.
- Ensure we have a passwd entry for a random UID, so that ssh works.
All of that is backwards compatible with the current container version
on privileged OpenShift.
Based on patch by Stef Walter, with some simplifications and adding the 
passwd fix.
=> tests: Fix container to work with unprivileged users

base/Dockerfile
We often process non-ASCII strings in our tests and logs.  Set a proper
Unicode locale to avoid Unicode{En,De}codeErrors.
---
We currently get a lot of failed test runs that just crash in the middle; [example](https://fedorapeople.org/groups/cockpit/logs/pull-9551-20180701-204949-872c225a-verify-fedora-i386/log):
```
Traceback (most recent call last):
File "/build/cockpit/bots/../test/verify/run-tests", line 66, in <module>
sys.exit(main())
File "/build/cockpit/bots/../test/verify/run-tests", line 63, in main
return run(opts)
File "/build/cockpit/bots/../test/verify/run-tests", line 43, in run
return testlib.test_main(options=opts, suite=suite)
File "/build/cockpit/test/common/testlib.py", line 1251, in test_main
ret = runner.run(suite)
File "/build/cockpit/test/common/testlib.py", line …
```
=> base: Set Unicode locale

release/Dockerfile, release/README.md, release/build-secrets, release/cockpit-release.yaml, release/node-stdio-wrapper, release/webhook
Add a script to turn a home directory with all the necessary credentials
into a Kubernetes secrets volume.
Add a GitHub webhook (using only Python 3 included modules) that can 
release any project with the Cockpituous release script. The git repo
URL is taken from the requests's GitHub metadata, and the path to the 
release script is taken from the URL path.
Document how to deploy this.
=> release: Add resources and webhook for running in OpenShift

tests/cockpit-tests
`git reset --hard origin/master` still leaves the current checkout in
"detached HEAD" state. This sometimes confuses git when testing a new
PR, it then tries to re-apply all commits of the entire history when
cockpit's tests-invoke tries to rebase a checked out PR onto current
master.
Do what we actually mean: First reset and clean up all changes from the
current checkout and then checkout the current origin/master.
=> tests: Properly reset HEAD of cockpit checkout

release/release-source
welder-web, starter-kit, cockpit-ostree, and similar don't use
autotools, but just a plain Makefile. Support these in release-source:
if autogen.sh or configure exist, do as before (i. e. for cockpit
itself), otherwise try `make dist` or `make dist-gzip`.
Disable patch generation for non-autotools projects, as there is no
predictable way to do out-of-tree builds for them.
=> release: Make release-source work for plain Makefile projects

tests/cockpit-tests
starter-kit and similar project tests run
git fetch --depth=1 https://github.com/cockpit-project/cockpit.git 172
to do a shallow checkout of cockpit's bots/ directory for running their
test. git remembers this and does not fetch the full origin again even
after `git fetch origin`. While there are ways to un-shallow a checkout,
this is brittle and also does not happen too often (as the majority of
our tests are still from cockpit itself).
To avoid "rebase" errors for subsequent test runs, do a clean re-clone
of cockpit if there are any "grafted" commits, i. e. the oldest commit
from a previous shallow clone.
=> tests: Do a clean clone if origin is shallow

release/release-runner
This causes eternal hangs, as an EOF on stdin is then not sufficient any
more to shut down ssh.  This can easily be demonstrated with
echo whoami | ssh -tt somehost
This was introduced in commit 3f2c177abfff for release-debian. But this
has been gone for a  while, and there is no real justification to do
that -- nothing in our release scripts ought to need a PTY, and if there
is anything that should be wrapped in `script` or similar.
=> release: Don't force ssh TTY

release/README.md, release/release-srpm
starter-kit based projects do release tarballs with spec files that
already have a correct `Version:` instead of `0`. This makes them more
self-contained and able to build working (s)rpms without the help of
cockpituous.
Support this mode with a new `release-srpm -V` option. By default,
release-srpm would generate a spec file with `Release: 2` as it assumes
that `XXX-1` was already released. `-V` tells it that the `Version:` is
already correct and it should leave the `Release:` at 1.
=> release: Support spec files with pre-filled Version:

release/release-source
If ./autogen.sh is available, prefer that over calling ./configure when
building patches. Otherwise changes to autotools input files
(configure.ac) will not end up in generated patches.
=> release: Force autoreconf in patch creation

tests/Dockerfile
This will be necessary for updating translations with zanata-js for
welder-web.
Fixes #197
=> tests: Install C/C++ compiler and jq

Makefile, release/README.md, release/release-runner
Cockpit's cockpituous release script was moved into tools [1], so adjust
the documentation accordingly.
[1] https://github.com/cockpit-project/cockpit/pull/9914
=> release: Adjust to moved Cockpit release script

release/release-bodhi
In the past two years there has never been a case where we had to recall
a Cockpit update, and pushing it to stable is an extra manual step that
one must remember. Let this happen automatically now.
Note that a bad update can still be blocked by a single -1.
=> release: Enable automatic landing in bodhi

release/release-runner
This is useful for cutting releases from stable branches, which just
receive some cherry-picks. This is more practical and robust for
downstream packaging than having to carry huge patches against dist/.
It's also very difficult to carefully tweak all file time stamps to not
trigger webpack when patching - this approach avoids this entirely.
=> release: Add option to release from a non-master branch

release/release-runner
Turns out that we don't actually need this. We should rather specify the
tag explicitly with `-t`, which is more robust and also works with the
webhook.
This reverts commit abafb73611d549bd0236a9ef86de9c8550abc204.
=> Revert "release: Add option to release from a non-master branch"

release/Dockerfile, release/webhook
The webhook receives the pushed tag name in the payload:
```json
{
"ref": "176",
"ref_type": "tag",
[...]
```
Pass this on to the release runner through its `-t` option. This allows
us to do releases from stable branches when they get tagged there. For 
the usual "release latest tag on master" there should be no change.
=> release: Call release-runner with tag name in webhook

images/cockpit-images.yaml
Pods can fail at any time, e. g. our solitary "images" pod got killed
the other day when the underlying node went away. So wrap it in a
replication controller with one replica (which is sufficient for our
purposes).
Fixes #196
=> images: Use ReplicationController

tests/cockpit-tasks-centosci.yaml
This was lost in translation between my original PoC and bouncing it between Sanne and me.
Right now it seems to work anyway, as apparently oci-kvm-hook got deployed everywhere. But let's be explicit about it anyway.
=> tests: Make sure we run on Centos CI nodes that expose /dev/kvm

release/Dockerfile, release/README.md, release/build-secrets, release/cockpit-release.yaml, release/github_handler.py, release/webhook
See individual commits.
I rebuilt and uploaded the cockpit/release container, deployed it on our CentOS CI, and tested it with a fake release of my https://github.com/martinpitt/cockpit-ostree fork. Version 177 was successfully released on [GitHub](https://github.com/martinpitt/cockpit-ostree/releases) and [COPR](https://copr.fedorainfracloud.org/coprs/martinpitt/welder-web/package/cockpit-ostree/), which proves that secrets and the general webhook/release process work.
Full release log: https://fedorapeople.org/groups/cockpit/logs/release-177/log
=> Various improvements to release container

release/Dockerfile, release/cockpit-release.yaml, release/job-service-account.yaml, release/release-runner, release/webhook
See https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
This provides several benefits:
- Allow multiple releases to happen in parallel. Right now, pushing a
release tag to one project while another release is running (or 
hanging), will be silently ignored.
- Simplify/robustify the structure of our webhook, as a release request
does not need to be handled synchronously.
- Separate the credentials for the webhook and all the release secrets,
providing better isolation in case the web server gets compromised.
In cockpit-release.yaml, drop the release secrets and use the new 
"create-job" service account.
Copy webhook's home directory initialization logic to release-runner, so
that this can run in a freshly spawned cockpit/release container with …
=> release: Use Jobs to spawn release-runner in separate containers

learn/cluster.py, learn/extractor.py, learn/train-tests
The current DBSCAN model tries to do a full matrix of all
distances in the training data. Lets just limit to the most
recent N data items. Otherwise the size of the model
and runtime becomes unwieldly.
Hopefully we can eventually migrate to a more efficient
clustering algorithm or implementation.
=> learn: Add simple limit to amount of training data

.gitignore, learn/Dockerfile, learn/lighttpd.conf
Otherwise Python barfs when in Openshift due to not being able to find the user site-packages
=> learn: Add a HOME directory environment variable

tests/Dockerfile
This allows the container to run cypress.io tests. It's not currently
clear if and how much we are going to use it, but we at least want to
experiment with it and offer it as an alternative for external Cockpit
projects.
--- 
See https://github.com/cockpit-project/starter-kit/pull/50
Also a second commit to toss out the unnecessary kernel package.
=> tests: Install cypress.io dependencies

tests/cockpit-tests
So that they are protected from whatever happens inside the cockpit/
checkout.  For example, the cockpit/ checkout might run tests on a
branch with a version of the bots that are too old.
=> tests: Copy bots from their own checkout

sink/sink
Right now it just says
Expected [expected data] but not present
Also show what the actual state is, so that we can debug what's going
wrong with collision detection.
=> sink: Improve error for state collisions

tasks/webhook
This is useful to be able to restart a failed release. Otherwise that
will fail because the release job already exists.
=> tasks: Delete job object before creating it

tasks/Dockerfile
We need this for validating AppStream metadata, see
https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/#_app_data_validate_usage
=> tasks: Install libappstream-glib

tasks/cockpit-tasks-bos.yaml, tasks/cockpit-tasks-centosci.yaml
The GitHub token has moved to the webhook secrets a while ago, and
the copy got dropped from the tasks secrets.
=> tasks: Mount webhook secrets into tasks container

release/release-srpm
This causes rpmlint warnings:
cockpit-composer.src:4: W: mixed-use-of-spaces-and-tabs (spaces: line 4, tab: line 2)
Keep the alignment for a 17-character first column, as we use in cockpit
and welder-web.
=> release: Don't put tabs into .spec files

release/Dockerfile
Recently, the container build started to fail with
Problem: problem with installed package whois-mkpasswd-5.4.1-1.fc28.x86_64
- package whois-mkpasswd-5.4.1-1.fc28.x86_64 conflicts with expect provided by expect-5.45.4-1.fc28.x86_64
We don't need mkpasswd, so remove it first.
=> release: Fix container build

tasks/Dockerfile, tasks/webhook
Do the "[no-test]" check later, to avoid short-circuiting the git
update.
=> webhook: Update checkouts when merging no-test PRs

tasks/Dockerfile
There are too many cockpit test failures with Fedora 29 (e. g. qemu
monitor API), these need to be sorted out first.
=> tasks: Revert to Fedora 28

images/nginx.conf
Sometimes a cockpit/images container is used as a log sink as well,
and then we want files like "log", "status", and
"TestStorage-blah.FAIL.log" to be served as text/plain.
=> images: Serve files under /logs/ as text/plain

tasks/Dockerfile
The `npm install` was meant as pre-caching in the past, but it is moot
now: cockpit-tasks runs `git clean` as pretty much the first thing it
does. The webhook container entirely ignores this and does its own 
checkout. So let's save these > 400 MB from the docker image.
Also drop the checkout -- cockpit-tasks will do that, it doesn't take
long, and it's never going to be really useful as-is, as it quickly gets
out of date.
=> tasks: Drop cockpit checkout and npm install

tasks/Dockerfile
It was previously pulled in through a dependency. Cockpit's
atomic.bootstrap uses that, and replacing it with curl is a bit
inconvenient.
=> tasks: Add wget

release/release-runner, tasks/Dockerfile, tasks/webhook
If a release fails, the release container stops and makes it hard to
debug the failure or finish the release manually. For that, introduce a
new `-s` (sit) option that will sleep indefinitely instead.
As with a sink the actual release-runner runs in a subprocess, we can't
just pass a variable to the parent; so let the child process remove a
temporary flag file on success.
Enable this option in the webhook.
=> release: Add option to sit on failure

tasks/Dockerfile, tasks/webhook
Tests-scan also checks the labels, but apparently /issues/#/labels is
not synchronous right at PR creation. This caused interactively created
PRs with the label to still get all test requests.
=> webhook: Check payload for no-test label

tasks/webhook
GitHub webhooks suffer from a race condition: When getting a PR event,
calling the API about that very PR often delivers outdated results.  But
the webhook event already gets the entire `pull_request` object as part
of its payload, so let's just use that instead of querying it from the
API again.
https://github.com/cockpit-project/cockpit/pull/11556 introduced a new
`--pull-data` option to tests-scan, so pass the data to it.
This also finally obsoletes checking for the no-test label, so revert
commit f7918f6af.
Fixes https://github.com/cockpit-project/cockpit/issues/11554
=> webhook: Use tests-scan --pull-data option

tasks/cockpit-tasks
This hasn't worked for a long time, as our containers cannot run sudo.
VMs work fine, so this is obsolete.
=> tasks: Drop obsolete libvirt hack

tasks/README.md, tasks/install-service
- Pass the webhook secrets as a volume
- Pass our CentOS-CI AMQP server
- Switch to our current sink
- Drop obsolete --privileged and --uts options, our containers run fine
unprivileged
- Set default TEST_JOBS to 8, which is right for our beefy machines
- Use a systemd template unit, and run three instances on every host
=> tasks: Update manual docker mode

push-container
This was broken when both were installed.
=> push-container: Fix choosing podman / docker

tasks/install-service
This makes it possible to roll out a new container with a simple service
restart.
=> tasks: Ensure cockpit-tasks@.service has the latest image

Makefile
Add missing --shm-size, as docker defaults to 64MB which is too small
for chromium. Drop the obsolete --privileged and --uts options.
This brings this command in sync with tasks/install-service and the
OpenShift deployments.
=> tasks: Fix `make tasks-shell`

tasks/cockpit-tasks
It's a bit unnerving having to wait for up to five minutes when
deploying new containers, and it's also not really necessary at that
time.
=> tasks: Shorten initial sleep

tasks/install-service
The `docker pull` operation usually takes more than one minute if it
actually has to pull the container. Don't let the service fail because
of that.
=> tasks: Increase systemd unit timeout

images/Dockerfile, release/Dockerfile, tasks/Dockerfile
docker creates anonymous, but persistent volumes for all `VOLUME` paths
that don't get an explicit one with `--volume`. These slowly pile up and
lead to `ENOSPC` errors on the hosts.
This mostly affects tasks' /tmp, but it also makes little sense to
create external anonymous volumes for the secrets when they don't get
specified (for manual usage).
=> Drop unnecessary volumes

tasks/install-service
Commit ab56ed3a08 dropped the automatic volume for /tmp. This caused
weldr/lorax tests to run out of space, as they need lots of temporary
space. Configure the container to have 50 GB root fs space instead of
the default 10 GB.
This is simpler than re-introducing a /tmp volume and having to clean it
up manually.
=> tasks: Increase root fs size

tasks/Dockerfile
This has the cloud credentials for running lorax'es cloud image tests.
=> tasks: Add secrets symlink for lorax-test-env

Makefile, images/Dockerfile, images/install-service, sink/sink-centosci.yaml, tasks/cockpit-tasks-centosci.yaml
As both of our external sinks are not working, create our own as OpenShift pod. This unfortunately does not work remotely (i. e. for our BOS cluster), but it's at least a better permanent solution for CentOS CI.
This is all rolled out: container rebuild, resources deployed, running. E. g. [log](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12109-20190621-132121-c86fb7f0-cockpit-project-cockpit-podman-cockpit-fedora-30/log) from PR #12109
=> Add sink OpenShift resource

tasks/Dockerfile, tasks/webhook
The python3-pika package now supports SNI extension.
=> tasks: Use pika from the official repository

tasks/cockpit-tasks-webhook.yaml, tasks/webhook
After commit 6fea47f28 we now have a local sink, which is more robust
than a remote one. Similarly to CentOS CI tasks (commit 702389db),
switch the default release sink to the local service.
=> tasks: Change default release sink to cluster-local sink

tasks/cockpit-tasks, tasks/install-service
For the Red Hat internal tasks machines we want to use an internal
mirror to lessen the strain on npmjs.com.
=> tasks: Support custom NPM registry

tasks/cockpit-tasks
Using a non-default registry may need a custom SSL certificate. If
present in the secrets, set it through `$NODE_EXTRA_CA_CERTS`.
https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file
=> tasks: Support extra CA for custom npm registry

tasks/cockpit-tasks, tasks/webhook
TODO after:
My only concern is that this kinda messes with the whole chances system. Maybe po-refreshes and other tasks would get drowned out too much.
Currently `https://github.com/Gundersanne/cockpituous/tree/simulate-cockpit-bots` is running on some of our CI to simulate `bots/` being a separate project. This seems to be running fine.
=> tasks: Adapt to standalone bots project

push-container, tasks/cockpit-tasks
Only copy our bots checkout into a project directory if it the target
isn't the bots project  itself.
Also drop the redundant explicit `run_one_task()` call for bots, the
loop below will do that as the first thing.
=> tasks: Stop copying bots into bots

tasks/install-service
This makes it easier to integrate this into Ansible playbooks.
=> tasks: Allow npm registry and #instances to be set from environment

tasks/Dockerfile
It recently fell out of cockpit master's build dependencies [1]. Put it
back for the stable cockpit rhel-7.x branches.
[1] https://github.com/cockpit-project/cockpit/pull/12979
=> tasks: Add back intltool

tasks/Dockerfile
`zanata-client` does not exist in Fedora 31. Also it requires a lot of
java deps.
`python3-zanata-client` provides `zanata` cli tool.
For now lets have both until all projects migrate to this new zanata
tool.
I'll build and deploy this, then open PR in cockpit which will use this new tool and if that refresh works, then we can land this.
=> tasks: Add new zanata client

tasks/Dockerfile
Install Firefox 69, since 70 has broken cdp, see https://bugzilla.mozilla.org/show_bug.cgi?id=1593226
=> tasks: Lock down to older version of Firefox

sink/sink, sink/test-logic, sink/test-sink
This is currently a hidden mine: As soon as we'll rebuild the cockpit/images container, this will break the sink.
=> Fix sink on Fedora 31

tasks/install-service
podman in RHEL 8.0 does not yet have the `podman network` commands, so
the containers' networks cannot be isolated in the same way as with
docker. But it does already know about the SLIRP networking, so use
that.
It's more CPU intense than proper kernel bridges, but that doesn't
matter much (it only affects our fallback AWS cloud right now). Let's
move that back to "podman network" once we can rely on RHEL/CentOS 8.1 or
Fedora ≥ 30 on our infrastructure.
=> tasks: Isolate containers from each other with podman

tasks/cockpit-tasks
So we are able to do `git push` directly.
See https://manpages.ubuntu.com/manpages/precise/en/man1/git-credential-store.1.html
=> tasks: Use git credentials store

sink/sink
Fixes this crash:
```
File "./sink", line 624, in <module>
main()
File "./sink", line 607, in main
if status.begin(line, log):
File "./sink", line 352, in begin
self.push(data, log)
File "./sink", line 343, in push
traceback.print_exc(file=log)
File "/usr/lib64/python3.6/traceback.py", line 163, in print_exc
print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
File "/usr/lib64/python3.6/traceback.py", line 105, in print_exception
print(line, file=file, end="")
TypeError: a bytes-like object is required, not 'str'
```
=> sink: Fix writing exceptions into log

tasks/install-service
This prevents broken processes (such as firefox on some of our CI
machines) to block other tests and take unnecessarily long to die.
=> tasks: Limit systemd task containers to 16 GiB RAM

images/nginx.conf
Without that, they got served as application/gzip and thus could only be
downloaded. Like that they can be watched inline in the browser
conveniently.
=> images: Properly serve compressed log files

release/release-dockerhub
`LABEL` only officially suports the `=` form. `ENV` still supports both [2],
but let's just be consistent.
[1] https://docs.docker.com/engine/reference/builder/#label
[2] https://docs.docker.com/engine/reference/builder/#env
=> release: Consistent VERSION/RELEASE replacement

sink/sink
That's a more distinctive error code than 1, which happens for any
random crash. We want to be able to detect collisions in bots'
publish-wrapper. See https://github.com/cockpit-project/bots/issues/697
for details.
=> sink: Exit with code 77 on collision

tasks/Dockerfile
Use rsync to copy file and folder inside "bots" to "test" folder.
All test related libs will be imported from "test/bots"instead of "bots" in both cockpit-CI and "gating".
No "git clone/fetch" is needed in "gating" test environment.
Use rsync not cp because rsync is better than "cp" + "mkdir".
Why not move the whole bots folder into test? Two reasons:
1. Too big, especially "images" folder
2. Keeping bots in "root" will be easy and convenient for us to debug and run lots of "smart commands"
Here's a `Makefile` target to run rsync:
```
machine: bots
rsync -avR --exclude="bots/machine/machine_core/__pycache__/" bots/machine/testvm.py bots/machine/identity bots/machine/cloud-init.iso bots/machine/machine_core bots/task/testmap.py test
```
I did not push this update into PR …
=> tasks: Install rsync into cockpit-CI environment

release/README.md, tasks/cockpit-tasks
Cockpit-composer is migrating from the weldr to the osbuild github organization so its github url has changed. The references to weldr/cockpit-composer are changed to osbuild/cockpit-composer.
This PR should not be merged until after cockpit-composer has moved to the osbuild organization.
=> Update cockpit composer urls for organization change 

tasks/Dockerfile
The previous one does not exist any more.
=> tasks: Use a different Firefox 69 build

tasks/cockpit-tasks
A lot of tasks, particularly failed test runs, tend to leave temporary
files behind. This is particularly painful for VM overlays, which fill
up the /tmp/ tmpfs.
=> tasks: Clean temporary work dir between tasks

tasks/Dockerfile
=> tasks: Update to Fedora 32

tasks/Dockerfile, tasks/install-service
This will finally get us off the old version 69.
https://bugzilla.mozilla.org/show_bug.cgi?id=1593226 was fixed, so
versions ≥ 77 work again for testing Cockpit.
Unfortunately neither upstream beta nor Fedora downstream builds contain
the remote debugger any more, thus we are forced to use nightlies now.
=> tasks: Update to Firefox nightly builds, prepare for $TEST_DATA elimination

release/release-source
Don't run `make` with `V=1`. There are no surprises in the build log
during a release, and no unit test runs either.
This reduces the release log by ~ 90%.
=> release: Quiesce make

tasks/README.md
Merely setting up the webhook is not sufficient. You also need to add
cockpituous as a collaborator and set up the bots test map.
=> tasks: Document how to integrate a new project into CI

release/release-bodhi
Otherwise updates are not directly pushed to stable after 7 days.
This used to work but is not for at least the last month. No idea though when or why it changed, maybe it is a bug-report candidate?
But in any case `--autotime` cannot hurt.
=> release-bodhi: Use `--autotime` option

images/cockpit-images.yaml, tasks/README.md, tasks/cockpit-tasks-webhook.yaml, tasks/install-service, tasks/webhook
This avoids circling through all available registries, and prevents
accidentally using a wrong image.
Also drop the duplicated non-locked docker pull in
tasks/install-service.
=> Specify docker.io registry on container image pulls

tasks/cockpit-tasks-centosci.yaml, tasks/cockpit-tasks-psi.yaml, tasks/install-service
With the current combination of chromium, `$TEST_JOBS`, and cockpit
tests, the tests ran into the oom-killer a lot with 16 GiB, causing a
lot of "weird" and unspecific test failures. Bump to 24 GiB.
=> tasks: Bump container RAM

release/Dockerfile, release/release-runner
These make the container easier to use with local podman, in GitHub actions, and GitLab pipelines.
It also updates the container to Fedora 32 (implicitly, as we use `fedora:latest`).
=> release container updates

release/Dockerfile, tasks/Dockerfile
The node-sass NPM package contains/builds ELF binaries, which is
problematic for some distributions. Let's move from node-sass to
sassc, which is packaged in all major distributions.
Install sassc into the tasks container so that packages can start using
it.
=> release, tasks: Install sassc

tasks/webhook
Releases are now done through GitHub actions for each project.
-----
After that, the webhook by and large just feeds the JSON payloads into an AMQP queue, so it's very generic. We could replace it with an AWS lambda thing or something else which is "not our code". The only cockpit specific thing that it does now is to "cold-boot" the queues, i.e. call {tests,issue}-scan at the beginning. If our webhook replacement is going to be basically "always there", we could dispense of it.
But a better idea woud be to try and teach this to the tasks containers: they could check if AMQP queues don't exist yet, and if not, initialize them and call -scan at the beginning. @Gundersanne , WDYT?
=> tasks: Drop release from webhook

Makefile
Add the missing registry name, to be consistent with all the other tags
and making the push to dockerhub actually work.
=> Fix "latest" tagging of images

tasks/cockpit-tasks
All projects moved away from .tasks to GitHub workflows.
=> tasks: Drop .tasks file support

tasks/README.md
These moved to GitHub actions, and commit c5e378cf2c1e dropped support
for releases. This also means that the URL path of the webhook is now
meaningless.
Adjust the webhook URL to our current OCP4 deployment.
=> tasks: Drop documentation of automated releases

.github/workflows/build-release.yml, Makefile, push-container
We only use the container in GitHub workflows now, so it makes sense to
keep the image in the nearby registry. This also avoids running into
pull rate limits on docker.io.
Add a manually triggered "build-release" workflow that will allow us to
conveniently build and push a new image from a branch.
=> release: Move to GitHub registry, add build workflow

.github/workflows/build-tasks.yml, Makefile, ansible/cockpituous/images.yml, ansible/maintenance/deploy-tasks-container.yml, tasks/README.md, tasks/cockpit-tasks-centosci.yaml, tasks/cockpit-tasks-psi.yaml, tasks/cockpit-tasks-webhook.yaml, tasks/install-service
Our internal e2e machines can't pull from docker.io any more due to the
pull rate limits. Move them to https://quay.io/repository/cockpit/tasks
now.
Add a manually triggered "build-tasks" workflow that will allow us to
conveniently build and push a new image from a branch.
=> tasks: Move to quay.io registry, add build workflow

ansible/roles/cockpit-copr/tasks/main.yml
Apparently the default on the base image has changed, and the role
previously failed with:
```
TASK [cockpit-copr : Install Cockpit] ****************************************************************************
fatal: [ec2-50-19-34-50.compute-1.amazonaws.com]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for cockpit-234-1.el8.x86_64"}
```
=> ansible/cockpit-copr role: Disable GPG check

tasks/Dockerfile, tasks/README.md, tasks/cockpit-tasks
With these, developers can run a cockpit/tasks container pretty much
anywhere to do Cockpit development. This works well on our e2e machines
or for toolbox. Further packages can always be installed with
`docker exec -it -u root`, but these provide the most important tools.
Fix ~user home directory permissions, so that tmux and ssh work.
Configure kerberos to use a file ccache, as nothing else (reliably)
works in a container.
A comfortable and recommended workflow is to start the container in the
background and (re)attach to it through byobu. Add a `DEV` run label
with a comment to show how this works. Do *not* pass in the production
cockpit secrets, developers ought to use their own token in such a
situation.
-----
This also fixes the tasks container to Just Work™ with toolbox:
toolbox …
=> tasks: Add packages and configuration for interactive development, fix for toolbox

tasks/Dockerfile, tasks/install-service
- CentOS CI [successful](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-14913-20210112-092157-7de669da-fedora-coreos/log.html) [tests](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-14913-20210112-092154-7de669da-ubuntu-2004/log.html)
- [firefox on e2e](https://logs.cockpit-project.org/logs/pull-15125-20210112-095932-b037f913-fedora-32-firefox/log.html) successful test
- [RHEL on e2e](https://logs.cockpit-project.org/logs/pull-15125-20210112-095932-b037f913-rhel-8-4/log.html) successful test
=> tasks: Update to Fedora 33

.github/workflows/tests.yml, .gitignore, Makefile, tasks/README.md, tasks/cockpit-tasks, tasks/cockpit-tasks-webhook.yaml, tasks/credentials/generate-ca.sh, tasks/credentials/openssl.cnf, tasks/credentials/webhook/generate.sh, tasks/run-local.sh
I would like to make our tasks container self-testable, and run integration tests on tasks container refreshes and changes to the logic eventually. This is as far as I got today. It's not yet self-testing, but at least one can now run it locally in a very easy way. Please test it and let me know how it works for you!
=> tasks: Various fixes and improvements; add script to run AMQP+tasks locally

.github/workflows/tests.yml, sink/sink
As mentioned in #359, now that we have a workflow on PRs anyway, let's run the unit tests there as well. With that we have everything CI related inside our repo again.
=> Fix and run unit tests as GitHub workflow

ansible/inventory/e2e, ansible/maintenance/sync-secrets.yml
The tasks/webhook secrets are now in the internal CI secrets git
repository. Change sync-secrets.yml to get them from git, stop
considering cockpit-9 as the "holy master copy", and treat all machines
equally.
----
I ran this on my machine and rolled it out everywhere.
=> ansible: Get secrets from git, fix image containers after secrets update

.github/workflows/tests.yml
For an actual rebase to work, git insists on having an user name.
-----
Fixes [this failure](https://github.com/cockpit-project/cockpituous/runs/1769486155?check_suite_focus=true) when branches are actually out of sync with master. I deliberately made this to be an outdated branch, so that we can let this self-test.
=> Fix rebasing in tests workflow

images/generate-image-certs.sh, tasks/credentials/openssl.cnf
Remove the triplication of subjectAltName: Make
tasks/credentials/openssl.cnf's server_ca_extensions the single source
of truth, drop the unnecessary SAN from the AMQP client certificate, and
use it in the image certificate script as well.
This also avoids using /etc/pki/tls/openssl.cnf, which does not exist in
Debian/Ubuntu (i.e. on GitHub workflows), and we don't want to rely on
the system config anyway.
=> Clean up certificate SANs

.github/workflows/tests.yml, tasks/run-local.sh
This makes it easier to read the logs, as the lengthy container build is
then not part of the test log any more.
=> self-test code shuffle

.github/workflows/build-images.yml, .github/workflows/tests.yml, Makefile, images/Dockerfile, images/README.md, images/cockpit-images.yaml, images/install-service, sink/sink-centosci.yaml
Old container fails like this:
```
❱❱❱ podman run -it --rm -p 8080:8080 -u user -v ./local-data/secrets/tasks:/secrets:ro docker.io/cockpit/images 
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2021/01/28 10:11:10 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2021/01/28 10:11:10 [warn] 1#0: could not build optimal types_hash, you should increase either types_hash_max_size: 2048 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
2021/01/28 10:11:10 [emerg] 1#0: mkdir() "/var/lib/nginx/tmp/client_body" failed (13: Permission denied)
```
This is also what makes the workflow fail in PR #368. In GitHub's version of podman …
=> images: Fix container to run as user, test it in workflow, move to quay.io

.github/workflows/tests.yml, tasks/README.md, tasks/run-local.sh
- Create ssh config/key tasks secrets
- Expose port 8080 (as "image server") on the pod
- Start "cockpituous-images" container in the pod, configured like
sink/sink-centosci.yaml
- Tell tasks container to use it via `$TEST_PUBLISH`
- Do some coarse assertions about the sink's generated test logs
- Revert using the production sink secrets in the tests workflow.
This will mean the GitHub status URL is http://localhost:8080/...
which is a bit odd; but that address actually works if you run
run-local.sh manually locally, and for the workflow run it's not
really important to have the unit-tests log on the official sink.
It's much more important to exercise a changed sink interaction.
=> tasks: Deploy image/sink in run-local.sh

.cockpit-ci/run, tasks/run-local.sh
Create a GitHub token and corresponding htpasswd; the latter is
statically computed, as we don't want to introduce a `htpasswd` program
dependency, and reimplementing `$apr1` is too cumbersome. For that
reason, delay setting up the real GitHub token until the time when the
test touches the PR.
Test that image uploading and downloading works. This needs to happen in
a copy of the primary bots checkout, as the cockpit-tasks main loop
constantly resets this to origin/master; but we need to modify the bot
checkout's ca.pem to the locally generated one.
=> run-local.sh: Test image-{upload,download} and attachments

.github/workflows/tests.yml, tasks/run-local.sh
We also want to use this script to test a bots PR. For that we must
trigger the test on the bots repo, not cockpituous.
=> run-local.sh improvements, run it on every PR, fix container rebuild

tasks/credentials/openssl.cnf, tasks/run-local.sh
Wait for the images server to be fully up before calling image-upload.
In GitHub workflow it sometimes starts too late (perhaps because of
container image downloads happening in the background?)
Also add "cockpituous-images" to the list of valid DNS names covered by
the TSL certificate, so that we don't need to jump through hoops to use
curl directly.
=> tasks: Fix race condition in run-local.sh

tasks/run-local.sh
In <https://github.com/cockpit-project/bots/pull/1623> the bots testmaps
start to support injecting an additional test with
`COCKPIT_TESTMAP_INJECT=branch/context`. This allows run-local.sh to use
the same event/tests-scan workflow as production, without the `_manual`
testmap hack and calling tests-trigger.
The latter approach would not work at all for writing similar
integration self-tests for bots, as doing tests-trigger races with the
real bots (the bots repo has an issues webhook trigger, unlike
cockpituous).
=> tasks: Replace run-local.sh tests-trigger with testmap injection

ansible/aws/README.md, ansible/aws/launch-image.yml, ansible/aws/launch-tasks.yml, ansible/cockpituous/images.yml, ansible/cockpituous/sink.yml, ansible/cockpituous/tasks-systemd.yml, ansible/maintenance/sync-secrets.yml, images/install-service
I ran all affected playbooks and validated that they worked on our target machines. Among other things, this also finally replaced the docker.io/cockpit/images container with the quay one on our AWS sink and log servers.
=> Ansible deployment updates

tasks/run-local.sh
run-local.sh will also be used to test bots PRs [1], and that unit test
does not produce a test attachment.
[1] https://github.com/cockpit-project/bots/pull/1639
=> tasks: Restrict run-local.sh's attachment test to cockpituous PRs

ansible/aws/README.md, ansible/aws/sink-ssh-gateway.yml
This can be used to temporarily expose ports on workflow/pipeline
machines by doing port forwarding to our sink.
Create a new unprivileged user and use a separate key for this,  to get
proper privilege separation to the sink.
=> ansible: Add SSH gateway user/key to our sink

ansible/cockpituous/sink.yml
We shouldn't use `ansible_host` there, as that will be something clunky
like `ec2-<IP>.*.amazonaws.com` and not match the TLS certificate's
subjectAlternateNames.
Configure the logs.cockpit-project.org domain name instead. We had this
for  a long time, until the re-deployment earlier this morning changed
it.
=> ansible: Fix sink url pattern

tasks/cockpit-tasks
Commit 8b27da1eb44ff had a bug where the *first* cockpit-tasks round
always checked out the default branch of bots, instead of
`$COCKPIT_BOTS_BRANCH`. This led to bots PR failures when running
against an outdated master branch from a clone (as they usually are).
Fix that by using the `clone -b` option.
The bots checkout is now only for cockpit-tasks's benefit -- the
individual tasks and tests all check out their own bots. Thus we can
simplify `update_bots()` and only differ between "new checkout for the
first time" and "pull to get the latest version".
-----
Seen in [this bots PR](https://github.com/cockpit-project/bots/pull/1660) in [this workflow](https://github.com/cockpit-project/bots/pull/1660/checks?check_run_id=1871579295)
=> tasks: Fix and simplify bots checkout

tasks/run-local.sh
https://github.com/cockpit-project/bots/pull/1687 changes the default
AMQP server to the real official one on CentOS CI. Specify the local one
explicitly to avoid relying on the internal default.
=> tasks: Call inspect-queue on local AMQP server in run-local.sh

release/release-source
This fixes today's [cockpit release failure](https://github.com/cockpit-project/cockpit/actions/runs/575050528): Unlike our CI, release-source is doing an out-of-tree build, which somehow confuses our build system.
```
Traceback (most recent call last):
File "/build/source.5Z5zt7/repo/_build/../tools/build-debian-copyright", line 162, in <module>
license = module_license(moddir)
File "/build/source.5Z5zt7/repo/_build/../tools/build-debian-copyright", line 62, in module_license
raise SystemError('Could not determine license from %s' % moddir)
SystemError: Could not determine license from node_modules/@patternfly/react-core
```
PatternFly (and most other NPM modules) are not actually supposed to be in the dist tarball any more.
I also took the opportunity to throw out the 95% of cruft code …
=> Fix release-source for cockpit, massively simplify it

images/Dockerfile, tasks/run-local.sh
Use a multi-stage build [1], pick some "small container targetted" basic
packages, and remove some larger packages that we really don't need in
the container. This shrinks the container from 313 to 137 MB.
[1] https://docs.docker.com/develop/develop-images/multistage-build/
----
This was mostly a learning opportunity for me, I just saw @asamalik 's and @fatherlinux 's excellent [building smaller container images](https://devconfcz2021.sched.com/event/gmSS/building-smaller-container-images) devconf.cz talk. But then why not, now I earned some twitter bragging rights. :grin: 
I tested this locally, but our CI will test it in full.
=> images: Minimize container

ansible/maintenance/reset-docker.yml
Sometimes docker gets itself into a bad state where containers are bad,
undeletable, or starting/stopping them throws weird storage errors. This
playbook does a "factory reset". This removes all containers, images,
and volumes.
----
I just used that to repair some accrued damage on our e2e machines. Don't ask too much about the sleeps.. It was not totally obvious how to do that right, so I'd like to keep this as a recipe.
=> ansible: Add playbook to reset docker on e2e machines

ansible/maintenance/reset-docker.yml
The sleeps introduced in commit 83d8c4d9f81e7c were not necessary after
all, they were just a leftover when the commands were done in the wrong
order.
In addition, stop and restart the work containers.
=> ansible: Update reset-docker playbook

tasks/cockpit-tasks-centosci.yaml, tasks/install-service
Current cockpit tests often need a bit more than 10 GB as especially the
nondestructive VMs pile up a lot of cruft in their overlays.
----
I deployed this, and our tasks containers now have a 14 GB /tmp.
This happend particularly badly in https://github.com/cockpit-project/cockpit/pull/15484 , I'll now retry this PR to validate that it is enough.
=> tasks: Increase /tmp to 14 GB

ansible/maintenance/sync-secrets.yml
Updating the secrets directory yanks it away from existing running
containers and thus breaks them. Commit c78c681725b13 already fixed for
the images containers, but it applies to tasks as well.
=> ansible: Restart all containers in sync-secrets.yml

tasks/webhook
https://github.com/cockpit-project/bots/commit/7a3c71968d5684 moved the
testmap.
This is super-urgent, as the current webhook container fails to start, and thus we can't run any tests.
=> tasks: Adjust webhook's bots testmap import

tasks/run-local.sh
run-local.sh makes liberal use of containers with bind-mounted files and
directories from the host.  This is a recipe for disaster with SELinux enabled,
leading to messages about waiting for for RabbitMQ to come up.
Let's sprinkle -v :,z around everywhere to relabel the files in question.
Pretty much all of them are exclusively intended to be bind-mounted into
containers anyway.
There remain two issues to running this on a stock Fedora 34 Silverblue system:
openssl needs to be installed, and the python3 'yaml' module as well.  In both
of those cases, though, the error message is clear and the solution is obvious.
=> run-local.sh: fix SELinux label issues

images/nginx.conf
This makes it convenient to look at in a browser.
--
I tested this with a locally built container and a cobbled-together images directory:
```
❱❱❱ curl -k --head https://images-frontdoor.apps.ocp.ci.centos.org/prometheus
HTTP/1.1 200 OK
Server: nginx/1.18.0
Date: Wed, 17 Mar 2021 06:58:16 GMT
Content-Type: application/octet-stream
[...]
❱❱❱ curl --head http://localhost:8080/prometheus
HTTP/1.1 200 OK
Server: nginx/1.18.0
Date: Wed, 17 Mar 2021 06:58:28 GMT
Content-Type: text/plain
[...]
❱❱❱ curl -k --head https://localhost:8493/prometheus
HTTP/1.1 200 OK
Server: nginx/1.18.0
Date: Wed, 17 Mar 2021 06:58:44 GMT
Content-Type: text/plain
[...]
```
I also tested it with firefox, and the file can be watched inline. Right now https://images-frontdoor.apps.ocp.ci.centos.org/prometheus just gives …
=> images: Fix MIME type of prometheus file

tasks/cockpit-tasks, tasks/run-local.sh
I tested this locally with a hacked up secrets dir and a local container. The integration tests model the situation quite closely.
The "test local deployment" step now takes only 2:15 minutes instead of the previous 7 minutes. :tada:
=> tasks: Set up S3 secrets for OpenShift, stop iteration when receiving SIGTERM

tasks/cockpit-tasks, tasks/run-local.sh
Fix commit cce26c464: The files in /secrets from the OpenShift secrets
volume are themselves links to a hidden ..data/ subdirectory. This
caused `find` to see them twice, and ran into "ln: file exists" errors.
Use a glob instead, and protect against zero matches with `test -e`.
=> tasks: Fix OpenShift S3 keys setup

release/release-koji
As of today, Fedora dist-git FMF test plans have to specify a git repo
and fixed ref for where to find the tests to run.
(https://github.com/psss/tmt/issues/585)
We don't want to bump this manually on every release, so teach
release-koji to do that automatically for every old version that appears
in plans/*.fmf.
This can be dropped once there is a way to just run the tests from the
upstream tarball in the dist-git, or run any "pre-discover" code.
=> release: Bump FMF plan refs in release-koji

tasks/cockpit-tasks
At tasks container shutdown, also take a chance to run image-prune on
the S3 stores.
=> tasks: cleanup S3 as part of pruning

tasks/Dockerfile
So that we can check out from repositories that use git lfs.
Note: git lfs also uses hooks to perform its magic, but they seem to
be only needed when actually making changes to files tracked by lfs
and pushing them.  But simply cloning a reporsitory that uses lfs
works fine as long as the git-lfs RPM is installed and configured
globally (which happens during installation).
To setup up the hooks, we would need to run "git lfs install" in the
local repository after cloning.
=> tasks: Add git-lfs

ansible/aws/aws_defaults.yml
Move to the current 8.4 daily. The previous image was still 8.2.
----
I tested this today with an UX demo instance as well as a "big" tasks runner (as e2e broke down last night)
=> aws: Update RHEL AMI

metrics/metrics.yaml, metrics/prometheus-claim.yaml
Start collecting our CI metrics, so that we can soon deploy a public
Grafana instance.
----
I deployed this to CentOS CI, and it is happily runnning now. To validate the service you can `oc rsh` into e.g. a tasks pod and try `curl http://prometheus:9090/prometheus/`. To validate the import, you can run `oc port-forward metrics-7474b48bb-g6tmz 9999:9090` and poke around in http://localhost:9999, and e.g. graph `test_run_seconds_count`.
=> metrics: Add prometheus

Makefile, tasks/Dockerfile
=> tasks: Move to Fedora 34

ansible/aws/aws_defaults.yml, ansible/aws/setup-host.yml
The previous one wa for 8.4 beta, move to 8.4 released. On the former,
installing packages does not work any more.
----
I rolled this out on AWS for starting a tasks runner, as e2e is still down.
=> aws: Update default AMI

ansible/aws/launch-tasks.yml
200 GB was not enough for the number of tasks containers that the CPU
and RAM are capable of sustaining, so they kept running into ENOSPC.
---
I rolled this out earlier today, and at least that part works fine:
```
/dev/nvme0n1p2  800G   56G  745G   7% /
```
=> aws: Increase disk size of tasks runner

tasks/cockpit-tasks-webhook.yaml, tasks/run-local.sh
Today we ran into a failure on spawning the webhook container due to
pull request rate limits from CentOS CI. Avoid this in the future, and
use our container copy on quay.io instead.
----
=> tasks: Move to RabbitMQ container on quay.io

ansible/aws/README.md, ansible/aws/launch-demo.yml, ansible/aws/launch-public-sink.yml, ansible/aws/launch-tasks.yml, ansible/aws/launch-webhook.yml, ansible/cockpituous/webhook.yml, tasks/README.md, tasks/cockpit-tasks, tasks/cockpit-tasks-centosci.yaml, tasks/cockpit-tasks-psi.yaml, tasks/cockpit-tasks-webhook.yaml, tasks/credentials/openssl.cnf, tasks/install-service, tasks/webhook
Normally our webhook runs on CentOS CI, but that is a single point of failure. Add an AWS deployment as a fallback.
This is not very robust nor elegant yet, but good enough as initial emergency fallback.
=> aws: Add webhook

tasks/cockpit-tasks
Also ensure that there are no leftover VMs.
This may help with
Failed to connect socket to '/work/.cache/libvirt/libvirt-sock'
errors which have plagued us for a while. Normally libvirtd removes the
socket right before it times out, but either there is a race condition
which we hit often, or something removes stuff in ~/.cache/libvirtd/.
----
This is totally a shot into the dark, to fix failures [like this](https://logs.cockpit-project.org/logs/pull-15934-20210611-093034-a98e957e-fedora-34/log.html).
=> tasks: Kill libvirtd in between iterations

metrics/README.md, metrics/cockpit-ci.json, metrics/metrics.yaml
Enable anonymous access. Our raw metrics are public already anyway (on
purpose).
There is still some manual setup required for setting the admin password
and importing the Cockpit CI dashboard. Document these for the time
being.
-----
I already deployed this. See https://grafana-frontdoor.apps.ocp.ci.centos.org/d/ci/cockpit-ci and https://github.com/cockpit-project/cockpituous/tree/grafana/metrics to pre-view the documentation.
=> metrics: Add Grafana

tasks/webhook
Fetching http://webhook/inspect-queue should now display the output of
inspect-queue.
This lets us see what's in the queue without having to have secrets
setup locally.
=> webhook: add an /inspect-queue endpoint

.github/workflows/build-release.yml
This is now possible with the recently introduced fine-grained
permissions:
https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
----
I triggered a [container refresh](https://github.com/cockpit-project/cockpituous/actions/runs/1003193308) on that branch. It succeeded and [pushed a new tag to the registry](https://github.com/cockpit-project/cockpituous/pkgs/container/release).
Once this PR and https://github.com/cockpit-project/cockpit/pull/16051 both land, I'll delete `COCKPITUOUS_GHCR_TOKEN` from our org secrets and the secrets repo.
=> workflows: Use default GitHub token for pushing to ghcr.io

release/release-srpm
This bit us on the latest cockpit-ostree release.  Make two changes:
- use git (not sed) to strip the parts of the tag we don't care about
- use grep to force the correct format, instead of using sed to attempt to "fix" things
=> remove sedery from release-srpm

sink/sink
Use a regexp to find and blind strings which look like GitHub tokens.
At the point we apply the regexp, we're dealing with complete lines, so
we don't have to worry about the token having arrived in two separate
reads.
=> sink: avoid logging GitHub tokens

images/Dockerfile, tasks/run-local.sh
Fix the ~user/.config/github-token symlink to point to the correct
Kubernetes secret encoded file name, exactly like tasks/Dockerfile does.
Since a recent cleanup of our secrets,
secret_volume/.config/github-token has not existed any more. This
broke direct image uploads from tasks containers (which got hidden by
the images also uploading to S3), and sink status credentials (which got
hidden by tasks bots sending the token as part of the request, until
[1]).
Add a test to ensure that the images/sink container has a working token.
[1] https://github.com/cockpit-project/bots/pull/2186
----
[Image container rebuild](https://github.com/cockpit-project/cockpituous/actions/runs/1008311700)
=> images: Fix GitHub token symlink

.github/workflows/build-images.yml, .github/workflows/build-tasks.yml
These two workflows are now the only users of the quay.io robot token,
so it got moved from the cockpit-project org to a new cockpituous
"quay.io" environment.
----
I sent a corresponding PR to ci-secrets.git (internal) to move the secret into the github/env/ dir.
=> workflows: Run quay.io image builds in quay.io environment

metrics/README.md, metrics/deploy.sh, metrics/metrics.yaml, tasks/build-secrets
See individual commits. This morning was the second time when our https://grafana-frontdoor.apps.ocp.ci.centos.org/d/ci/cockpit-ci dashboard went AWOL and the admin user was reset to the default password. Now the whole deployment is automated.
I already rolled this out, and adjusted the secrets in the internal dir.
=> metrics: Automate remaining Grafana setup steps

.github/workflows/tests.yml
This avoids another usage of our cockpituous token.
---
I am not sure if we even want that -- it's kinda sorta a validation that our cockpituous token works and has the required privileges. But then again, we usually don't run a cockpituous PR test when we change the token (we usually learn about it because our tests explode :boom: ). So for now this is more of a "let's see if this even works" exercise.
If this works and we want it, I'll do the same to bots -- this test run is the only usage of the cockpituous token by cockpituous.git and bots.git, so it'll make it easier to move this into an environment.
=> workflows: Run deployment tests with default GitHub token

metrics/budget.json, metrics/deploy.sh
This expresses our SLIs in terms of how much of the error budget has
already been used, in a rolling "last N days" view. This allows us to
see the curren state (rightmost value), and see trends and thus predict
if we are going to exhaust the budget soon.
----
I deployed this with the usual `metrics/deploy.sh` and no further fiddling. Can be viewed at https://grafana-frontdoor.apps.ocp.ci.centos.org/d/budget/cockpit-ci-error-budget and of course also in the Dashboards index.
=> metrics: Add error budget dashboard

metrics/metrics.yaml
This provides much better contrast, in particular it makes warning
thresholds easier to see.
---
Already rolled out, as usual. Before I just changed that in the admin web UI.
=> metrics: Use light Grafana theme by default

tasks/cockpit-tasks-webhook.yaml
The default is 30 minutes, which is too short for most of our tests.
Increase it to 2.5 hours, which is our 2 hour global test timeout plus
some extra setup/teardown. This does not need to be particularly tight,
as broken bots will be considered dead quickly due to missing
heartbeats.
See https://www.rabbitmq.com/consumers.html#acknowledgement-timeout
-----
This will hopefully address the many "duplicate test runs" problem that we've seen for some time. [latest example](https://logs.cockpit-project.org/logs/pull-16117-20210719-165231-8be6c386-rhel-9-0/)
This is how to find them on our AWS sink:
find /var/cache/cockpit-tasks/images/logs/pull*20210720* -name backup*
(adjust or losen the date fnmatch accordingly)
I rolled this out, let's check if that really fixes it before landing.
In the …
=> tasks: Increase RabbitMQ ACK timeout

ansible/maintenance/reset-docker.yml
In all cases so far I actually want to reboot the e2e machines, instead
of restarting the bots right away. This cleans piled up cruft in the
kernel/kvm which tends to cause funny effects/breakage in docker over
time.
=> ansible: Reboot e2e machines in reset-docker.yml

tasks/run-local.sh
This is some initial work to make it easier to work with a local deployment. The first commit is huge, but it's really just moving code around into functions -- I did not make any "fine-grained" changes other than passing `"$@"` to `getopts` (that's a technical necessity for moving it into a function).
=> tasks-local.sh: Split into functions, add interactive mode

ansible/roles/install-secrets-dir/tasks/main.yml, ansible/roles/install-secrets-openshift/tasks/main.yml
@marusak : I tried running sync-secrets from my machine, and ended up with correct permissions (644 instead of 664). So this is a shot into the dark -- at least with this fix the files have the same permissions as before.
I also added a nice little tweak for OpenShift secrets which I learned from @mh21 today, thanks!
=> Two secrets fixes

release/release-source
If a (plain Makefile) project defines a `make node-cache` rule, then
call this during release-source. We will gradually add these to our
projects to fulfill Fedora's packaging policy.
Drop the requirement that there is exactly one tarball.
-----
I tested this with cockpit-certificates, see https://github.com/skobyda/cockpit-certificates/pull/65.
I also tested this with cockpit-podman (which does not have such a rule), and it correctly produces a single _release/source/cockpit-podman-34.tar.gz
=> release: Build a node-cache tarball in release-source

tasks/Dockerfile
It is a required build dependency for JS packages as per
https://docs.fedoraproject.org/en-US/packaging-guidelines/Node.js/#_buildrequires
---
Seen in/blocks https://github.com/skobyda/cockpit-certificates/pull/66
=> tasks: Install nodejs-devel

ansible/aws/aws_defaults.yml, ansible/aws/demo/2021-10-metrics.yml
Set up a few resource hogging services/containers for users to find and
identify.
Some parts should be started about 20 to 30 minutes before the test
begins, create an `~admin/demo-prep.sh` script for that. The test
conductor needs to run this manually.
------
I started this with
ansible-playbook -i inventory aws/launch-demo.yml 
ansible-playbook -i inventory aws/demo/2021-10-metrics.yml
which launched one machine. I then immediately ran
ssh admin@ec2-XXX-XXX-XXX.compute-1.amazonaws.com
sudo ./demo-prep.sh
@andreasn , @marusak: Can you please play around with that instance and see that it works as intended?
=> aws: Add metrics UX demo

tasks/Dockerfile
See https://bugzilla.redhat.com/show_bug.cgi?id=2013095
I built this locally and created a toolbox out of this. This works quite fine for starter-kit, machines, and cockpit itself, so I think it's ready.
=> tasks: Update to Fedora 35, downgrade Chromium to 93

ansible/inventory/e2e
These moved into a different DNS domain a few months ago, since then
the old names were not resolvable any more.
----
Tested with reverting my /etc/hosts hacks and `ansible -m ping -i inventory e2e`
=> ansible: Update cockpit-* e2e machine domain names

ansible/roles/install-secrets-openshift/tasks/main.yml, tasks/credentials/openssl.cnf, tasks/run-local.sh
This will fix image upload/download from cockpit-11 after the DNS change.
Currently, uploading fails in CI like this:
```
❱❱❱ curl --cacert ~/upstream/bots/images/files/ca.pem https://cockpit-11.apps.cnfdb2.e2e.bos.redhat.com:8493/
curl: (60) SSL: no alternative certificate subject name matches target host name 'cockpit-11.apps.cnfdb2.e2e.bos.redhat.com'
```
I ran images/generate-image-certs.sh in our secrets git, pushed the result, and re-deployed the secrets. This first failed due to a syntax error, fixed here as well.
Now the above curl command succeeds again.
=> tasks: Add subjectAltName for recently changed e2e domain

tasks/Dockerfile
Fedora's firefox packages have shipped DevTools support for a while, so
we can go back to testing stable versions instead of nightly ones.
Both of the previous Chromium crashes are fixed in current versions.
----
I tested this in my toolbox, with all four combinations of {chromium,firefox} x {headless,show}. I also ensured that removing the chromium package and only keeping chromium-headless works.
So let's build and roll out a container, we haven't done this in a while.
=> tasks: Go back to standard distro firefox and chromium packages

tasks/Dockerfile
flatpak implicit build dependency, but if not installed before,
the builddep command fails to resolve it, (at least on the local toolbox
cockpit container)
I tried using builddep command, but it fails resolving some of the
systemd nested deps (systemd is a build dependency of anaconda), but
since systemd is already installed, let's not try to install it again.
=> tasks: add anaconda project's build dependencies to container

metrics/cockpit-ci.json
The panel is a bar gauge which lists the slowest tests overall as
filtering is currently not possible. For filtering per project to work
we need to introduce a new metric which has a label for every project we
have. As label_values(top_failures_pct, project) is not the same as
label_values(top_slowest_tests, project).
The second issue is that a bar gauge can't be sorted correctly this is a
Grafana limitation. https://github.com/grafana/grafana/issues/17245
---
The dashboard now looks like 
As a follow up we should introduce a new metric (number of tests maybe?) which would have a label for every project we test.
=> Add a slowest tests panel to CI dashboard

tasks/webhook
We haven't done releases on our own infra for a long time, just PRs and
issues. Rename the webhook's handler class accordingly.
=> tasks: Update GitHub webhook handler class name

tasks/install-service
About half of our e2e machines ended up with tasks containers having
/tmp (where the QEMU overlays go) on spinning Rust, due to the "enough
memory available?" heuristic being tuned slightly wrongly. This led to
tests running very slowly and failing due to all kinds of timeouts due
to I/O contention.
Drop that heuristic, and run containers with a tmpfs on /tmp everywhere.
Both e2e and AWS machines have enough RAM, and if we run them anywhere
else we'll have to make sure to pick an adequate `$INSTANCES` for the
available RAM.
---
I rolled this out to our e2e machines:
ansible -i inventory/ -m include_role -a name=tasks-systemd e2e
and verified that all containers have a tmpfs /tmp. Let's see how tests perform now!
=> tasks: Default to using tmpfs for /tmp everywhere

tasks/cockpit-tasks
Commit db56f3bda introduced the killing of libvirtd after every test
run, to ensure to start from a clean slate and avoid race conditions.
Howver, in Fedora 35 (commit 864b51b06d), libvirtd got split into
multiple components.
Adjust to `virtqemud` and actually wait until the process is gone, to
avoid a race condition with accessing the socket.
---
We are currently [getting](https://logs.cockpit-project.org/logs/pull-16884-20220128-125225-d023f048-fedora-35-mobile/log) this test failure quite often:
libvirt: XML-RPC error : Failed to connect socket to '/work/.cache/libvirt/virtqemud-sock': No such file or directory
I have no idea why that happens. However, our original approach in commit db56f3bda stopped working with the upgrade to Fedora 35, and it was racy anyway.
=> tasks: Update to split libvirt daemon, wait for process

ansible/aws/README.md
The webhook gets called via http, not https (messages are signed by
the shared secret).
Replace the concrete IP address with a symbolic name, to avoid tricking
operators into copy-pasting it verbatim.
Explain how to revert the change, in particular the original CentOS CI
webhook address.
=> ansible: Update webhook documentation

ansible/aws/launch-tasks.yml, ansible/aws/tasks/launch-coreos.yml
Similarly to commit 9cccfd9, move launch-tasks.yml to launch-coreos.
Adjust the device name, as the root volume is now called /dev/xvda instead of
/dev/sda1 with CoreOS and the new ec2_instance API.
---
- Builds on top of PR #461 
I launched this, it started and immediately grabbed some work, for example [this](https://logs.cockpit-project.org/logs/pull-17035-20220223-084238-42d9c17e-fedora-35-devel/log.html) or [this run](https://logs.cockpit-project.org/logs/pull-17035-20220223-084238-42d9c17e-fedora-35-devel/log.html)
=> ansible: Use Fedora CoreOS for tasks

release/release-github
For a few months now, uploading tarballs to GitHub is irritatingly
brittle, and often fails with
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
Retry all API calls (including uploads) up to five times, with
exponential back-off.
Change the two instances where curl reads --data from stdin to read from a file
or a string, so that it actually becomes repeatable.
Fixes #457
=> release: Retry curl requests in release-github

release/Dockerfile
https://github.com/cockpit-project/cockpit/pull/16853
changed cockpit's template spec format and location. Adjust Dockerfile
accordingly.
Exactly the same fix as for the tasks container in commit 1d2baf3d99c8a7.
=> release: Adjust container build to changed cockpit spec file

Makefile, push-container
This was totally stupid of me.. Developers don't do that, but our
workflows use exactly that.
This reverts commit 59ac7910cf7ed0749d794577b41c5e17e92fb10a.
-----
see [refresh failure](https://github.com/cockpit-project/cockpituous/runs/5394619718?check_suite_focus=true) in #469
=> Revert "Drop push-container"

release/release-github
Commit d12ec62f97 added a retry loop around uploading tarballs to
GitHub. I renamed `$sleep` to `$retrysleep` after the first version to
avoid a naming collision/confusion with the `sleep` command, but forgot
a spot.
---
This [broke my release](https://github.com/cockpit-project/cockpit/runs/5403993979?check_suite_focus=true).
=> release: Fix undefined variable in release-github

.github/workflows/build-images.yml, .github/workflows/build-tasks.yml, Makefile, push-container, tasks/cockpit-tasks
Several of our tasks containers got stuck in an endless pgrep/sleep
loop, as the running virtqemud ignored SIGTERM and even SIGQUIT.
=> tasks: Kill virtqemud harder, fix image pull failure on RHEL 8

tasks/Dockerfile
libvirt-daemon-kvm is a meta-package that pulls in the qemu-kvm
metapackage (which has tons of desktop-only dependencies), plus all of
the storage/network libvirt drivers which we also don't need for
testing. This reduces the image size from 2.55 to 2.22 GB.
See https://libvirt.org/kbase/rpm-deployment.html
-----
- Depends on https://github.com/cockpit-project/bots/pull/3064
I locally built a container from this and ran a Firefox and Chromium test.
=> tasks: Avoid unnecessary qemu-kvm desktop/storage/network dependencies

ansible/aws/launch-tasks.yml, ansible/roles/tasks-systemd/tasks/main.yml, tasks/cockpit-tasks-centosci.yaml, tasks/install-service
With 5 parallel tests, cockpit tests often require more than an hour to
run, which exceeds our Service Level Objective [1]. Increase it to 8.
This reduces the number of running bots, and thus increase the queue
time when there is a lot of demand -- but while there isn't, we'll get 
feedback much faster.
Don't increase /tmp tmpfs size - 14 GiB should still be enough even for 
~ 15 VM overlays (for tests which start multiple VMs); they are not that
big, and projects which do produce a lot of data (such as
cockpit-composer) need to set `$TEST_OVERLAY_DIR` anyway.
Reduce the number of instances on the e2e and AWS machines to compensate
for increasing the test jobs.
Test on CentOS CI fail a lot with TEST_JOBS > 6, due to timeouts, fork()
failures, and VM boot timeouts, so only marginally …
=> tasks: Increase parallel jobs

tasks/Dockerfile
This is necessary to run
virt-install --os-variant fedora-rawhide --memory 2048 --noautoconsole --network none --location /tmp/fedora-rawhide-boot-*.iso
i.e. what Anaconda tests do.
---
The recent cleanup in PR #473 broke anaconda tests: [log](https://logs.cockpit-project.org/logs/pull-3959-20220315-112723-c6aa0907-fedora-rawhide-boot/log)
=> tasks: Put back libvirt storage driver

ansible/aws/tasks/launch-coreos.yml
This avoids hidden costs or accidentally blocked volume/IP resources,
and allows us to move to an elastic model especially for the tasks
runners -- then they can decide on their own for how long they want to
run.
---
Split out from PR #477 -- I did comprehensive testing there.
=> ansible: Terminate AWS instances on shutdown

ansible/maintenance/deploy-tasks-container.yml, tasks/cockpit-tasks-centosci.yaml
Our cockpit-tasks script already listens to SIGTERM for a graceful
shutdown, i.e. finish the current task and then stop the main loop.
Make use of this when we deploy a new container, instead of bluntly
killing them:
- For OpenShift, `oc delete` already SIGTERMs the container, but the
default grace period of 30s is way too short. Bump it to one hour,
which is our agreed-upon maximum test runtime.
- For systemd, signal cockpit-tasks instances (which we can see from
the host)
There is no big downside: After running the deploy script, the existing
running containers will not de-queue new tasks, i. e. all
subsequent tests will run on the new image. But we stop interrupting
running tests, having to re-start them and running our test stats.
----
I tested this both on OpenShift (config change …
=> tasks: Avoid test interruption when deploying a new container

metrics/metrics.yaml
The bitnami image ceased to exist.
---
I tested this first locally, and updated https://piware.de/gitweb/?p=learn-metrics.git . I rolled this out, and https://grafana-frontdoor.apps.ocp.ci.centos.org/d/ci/cockpit-ci?orgId=1 is now a thing again :partying_face:
=> metrics: Move to official Grafana container image on docker.io

tasks/cockpit-tasks, tasks/install-service
We are currently getting an awful lot of [npm install failures](https://logs.cockpit-project.org/logs/pull-3277-20220426-052741-a5434ecf-fedora-rawhide-boot-rhinstaller-anaconda/log.html) on our CI. Let's try to improve this.
=> tasks: npm install robustification

tasks/install-service
With our high parallelism, tests tend to run into a lot of errors like
this:
```
File "bots/machine/machine_core/ssh_connection.py", line 109, in wait_user_login
return self.execute("! test -f /run/nologin && cat /proc/sys/kernel/random/boot_id", direct=True)
File "bots/machine/machine_core/ssh_connection.py", line 332, in execute
proc = subprocess.Popen(command_line, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
File "/usr/lib64/python3.10/subprocess.py", line 966, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib64/python3.10/subprocess.py", line 1775, in _execute_child
self.pid = _posixsubprocess.fork_exec(
BlockingIOError: [Errno 11] Resource temporarily unavailable
```
in particular with Firefox tests (as Firefox tends to …
=> tasks: Increase PID limit

tasks/run-local.sh, tasks/webhook
tasks: Fix RabbitMQ/webhook startup race
tasks/cockpit-tasks-webhook.yaml starts the webhook and the Rabbit
containers at the same time. In most cases, RabbitMQ was not fully
running yet when the webhook container got to calling `tests-scan`, so
that the startup failed immediately with an AMQP connection failure.
Mitigate this by adding a waiting loop for AMQP being ready.
Move scan_tasks() below distributed_queue() as the former now calls the
latter.
Make this reproducible in tasks/run-local.sh by starting the webhook
container in interactive mode, and hand it the `-t` provided token, if
present. This is also a nice way of testing the queue scanning.
---
This broke the redeployment pretty hard last week. It was stuck in a long container crash/back off loop. It eventually worked after …
=> tasks: Fix RabbitMQ/webhook startup race

ansible/e2e/ntpd.yml
It was not running on several servers, which caused significant clock
drift. This caused S3 requests to fail, as request signature validity
is time dependent.
---
That is what caused these [RHEL image download errors](https://logs.cockpit-project.org/logs/pull-17334-20220512-071017-8ff38376-rhel-8-6/log.html)
=> ansible: Enable ntpd on e2e servers

tasks/run-local.sh
https://github.com/cockpit-project/bots/pull/3403 switches tests-scan
over to log to S3. Adjust run-local.sh's test_pr() for that. Create a
separate "logs" S3 bucket to mimic what happens in production.
Drop checking the "status" file, as the S3 stream does not do this.
-----
This should land shortly after https://github.com/cockpit-project/bots/pull/3403, and then without the XXX commit. But let's get this working first.
=> tasks: Switch run-local.sh to testing logs in S3

ansible/roles/webhook/tasks/main.yml, tasks/cockpit-tasks-webhook.yaml, tasks/run-local.sh
The webhook container can't and doesn't run behind the Red Hat VPN, so
the pull rate limits don't matter.
Our copy on quay.io is over a year old has several pending security
issues. Let's get rid of that.
=> Move to official RabbitMQ container image on Dockerhub

.github/workflows/tests.yml, ansible/inventory/e2e, ansible/roles/s3-systemd/tasks/main.yml, images/install-s3-service, tasks/README.md, tasks/credentials/openssl.cnf, tasks/run-local.sh
Configure/test `run-local.sh`'s S3 store to be suitable for production, and add scripts/Ansible to set up a production S3 on cockpit-11. I already deployed that. However, to use it, we still need some bots changes.
We also still need to keep the old images container until we move image refresh logs to S3 as well. After that, the prize money is [this commit](https://github.com/cockpit-project/cockpituous/commit/af43988407951b64e3da03e670bccf12f5148461) which removes all the images/sink stuff.
~After that lands, I'll drop the XXX commit and squash the fixup.~ **done**
=> e2e S3 sink for production

ansible/e2e/setup.yml
I ran this on cockpit-8, and I now see four lights^Wtask runners.
=> ansible: Set correct number of task instances for e2e machines

e2e/idrac/fragments/reboot.racadm
I used this today.  Maybe I'll use it again. :)
For the record, these get used like this:
```
./run-fragment idrac-cockpit-9 fragments/reboot.racadm
```
=> e2e: add "reboot" racadm fragment

ansible/maintenance/deploy-tasks-container.yml, tasks/cockpit-tasks, tasks/install-service
[example for corrupted NPM cache](https://cockpit-logs.us-east-1.linodeobjects.com/pull-585-20220613-053118-1f73e5dd-centos-8-stream/log.html), [example for socket timeout](https://cockpit-logs.us-east-1.linodeobjects.com/pull-584-20220613-055931-651370f8-centos-8-stream/log.html)
This addresses both issues. I've been deleting the npm caches quite often recently. I can't guarantee that per-task cache will help with that, but let's at least try. If not, I'll have to disable the persistent cache again, but it does greatly help with the timeouts.
I can reliably reproduce the socket timeout:
```
export NODE_EXTRA_CA_CERTS=/secrets/npm-registry.crt
git clone https://github.com/cockpit-project/starter-kit
cd starter-kit
git clean -ffdx; npm cache clean --force; time npm install
```
With the two …
=> Fight against npm install failures

metrics/README.md, metrics/metrics.yaml
https://github.com/cockpit-project/bots/pull/3511 moved the prometheus
export to our S3 bucket. Update our deployment accordingly.
=> metrics: Pull prometheus data from S3

images/install-s3-service
We previously handed the bare image cache directory to minio as data
volume. While this works fine for reading existing files through the S3
bucket, it doesn't for writing: Uploaded files get created as directory,
with some metadata and data possibly even split between multiple files.
Untangle that by using a persistent private volume for minio. With that,
the data volume file layout and also their permissions don't matter.
This causes some duplication between the volume and the cache directory
on the host, but we have tons of unused space on cockpit-11, so this
does not matter.
---
This fixes the systematic image download failures like [this one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3530-20220621-053636-ef3b8226-rhel-9-0-candlepin-subscription-manager/log.html) that …
=> images: Use private data volume for minio image store

ansible/e2e/setup.yml, ansible/roles/tasks-systemd/tasks/main.yml, tasks/Dockerfile, tasks/install-service
All our tasks machines run RHEL ≥ 8.6 or Fedora CoreOS now, so we can
rely on `podman network`. Use a bridge instead of slirp for more
performance.
----
This is the approch that we had used with docker for years. But our initial EC2 instances ran RHEL 8.4 or earlier, which did not have `podman network` yet, so I resorted to slirp.
I had this sitting on my disk for 2½ years, and just spotted this again when reviewing local branches. I rolled this out to e2e, and so far it seems happy. But let's give it a day or two of field evaluation.
=> tasks: Use "podman network"

.github/workflows/build-images.yml, .github/workflows/build-tasks.yml, .github/workflows/tests.yml, tasks/Dockerfile
Trying to build a Fedora container as root has started to fail in a
"funny" way: dnf immediately crashes with "sd-bus call: Connection reset
by peer".
Building and running the container as user has worked fine for a while,
and we do this everywhere else. It was originally introduced for a
missing slirp4netns package, but that got fixed in Ubuntu long ago.
----
Fixes [this failure](https://github.com/cockpit-project/cockpituous/runs/7337179255?check_suite_focus=true), which spontaneously broke around last week. I saw a similar effect in my [debugging saga with the unit-tests container](https://github.com/cockpit-project/cockpit/pull/17549#issuecomment-1182741018).
Tested all commits separately:
- [without tasks changes](https://github.com/cockpit-project/cockpituous/runs/7341492159?check_su …
=> workflows: Run tasks integration test as user

ansible/aws/README.md, ansible/aws/tasks/launch-coreos.yml, ansible/roles/webhook/tasks/main.yml
Our CentOS CI project will go away soon, so let's move to an EC2 instance as our primary webhook/queue. I deployed this already ([hello](http://ec2-3-228-126-27.compute-1.amazonaws.com/inspect-queue)), but didn't activate it yet in bots nor our projects.
=> Fix webhook EC2 deployment, move primary webhook to EC2

ansible/inventory/openstack.yml
Commit 232d5fca5 moved our OpenStack instances to CoreOS, but forgot to
adjust the inventory for existing instances. The default user on CoreOS
is `core`, not `fedora`.
----
This fixes running `deploy-tasks-container.yml` and other playbooks, which currently fail with SSH connection failures. Sorry for the hiccup!
=> ansible: Fix openstack inventory for move to CoreOS

tasks/Dockerfile
Apply the osinfo-db fix for recent Rawhide boot.iso images [1] until it
lands in Fedora [2].
[1] https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/481
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2103835
-----
=> tasks: Fix rawhide boot.iso virt-install

ansible/aws/tasks/launch-coreos.yml, ansible/roles/webhook/cockpituous-webhook.service, ansible/roles/webhook/tasks/main.yml
This makes our webhook instance robust for non-trivial lifetimes, as it is now our primary queue. This faces the public internet, so let's do the full treatment of automatic updates, automatic reboots, and automatic service starts.
I redeployed our webhook instance from scratch, and rebooted it to make sure that everything works. The queue is happy, and cold scanning GitHub looks as expected.
`zincati.service` is running, and `rpm-ostree status` confirms that it is armed:
```
$ sudo rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
DriverState: active; periodically polling for updates (last checked Tue 2022-07-26 12:47:55 UTC)
Deployments:
fedora:fedora/x86_64/coreos/stable
Version: 36.20220703.3.1 (2022-07-18T18:07:26Z)
BaseCommit: …
```
=> webhook instance: auto-updates, auto-start pods

tasks/Dockerfile
This got lost when updating to Fedora 36, as it is not installed by
transient dependencies any more. But at least cirros.bootstrap needs it.
----
Spotted in https://github.com/cockpit-project/bots/pull/3670 in a cirros test refresh, which [failed](https://logs.cockpit-project.org/logs/image-refresh-3670-20220729-065050/log):
```
+ genisoimage -input-charset utf-8 -output cloud-init.iso -volid cidata -joliet -rock user-data meta-data
/work/bots/make-checkout-workdir/images/scripts/cirros.bootstrap: line 24: genisoimage: command not found
```
=> tasks: Install genisoimage

ansible/roles/install-secrets-dir/tasks/main.yml
Previously, rolling out new secrets left the programs in the webhook
container crashing, as the secrets ceased to exist.
=> ansible: Restart webhook container on secrets rollouts

tasks/Dockerfile
cockpit-machines recently moved to using flake8 by way of cockpit's
static-code. But that runs in the tasks container, and thus is currently
skipped. Let's make sure it runs again.
- Blocks on https://github.com/cockpit-project/cockpit-machines/pull/788
=> tasks: Install flake8

ansible/aws/launch-webhook.yml, ansible/roles/webhook/cockpituous-webhook.service
It was broken again this morning, and already was brittle once last week. Trying to start the tasks container made podman crazy (spinning at 100% CPU) and filled up the disk. Day 2 operation lessons.. :grin:
I deployed this, and it has enough breathing room now.
/dev/xvda4       20G  2.7G   17G  14% /sysroot
=> Fix webhook container

ansible/maintenance/reset-npm-cache.yml
Occasionally, `npm install` starts failing like this:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/generator@^7.19.3.
This happens when its cache gets corrupted.
---
[recent example log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3915-20220929-105522-fd5e626c-fedora-coreos-cockpit-project-cockpit-ostree/log.html)
I already ran this to test it, so retrying the failed test should work now. But this needs to be run occasionally.
=> ansible: Add maintenance script to reset NPM cache volume

tasks/run-local.sh
When testing test/run we are not interested in flake8 or mypy errors, but want to run `test-bots`. This allows us to skip installing mypy in the tasks container.
https://github.com/cockpit-project/bots/pull/3735/commits/e1fc3e8bc9a7a38a6404762481ae8b65faa4b4a6
=> tasks: skip flake8/mypy for bots

.github/workflows/build-images.yml, .github/workflows/build-tasks.yml, .github/workflows/tests.yml
actions/checkout@v3 uses nodejs 16 as runtime instead of the deprecated nodejs 12 runtime.
=> .github: update checkout action to v3

tasks/Dockerfile
This way, we should be able to see CJK fonts instead of boxes in pixel test images, making it more likely to spot various issues involving non-latin languages.
=> Add CJK fonts to task container

tasks/Dockerfile
Since https://github.com/rhinstaller/anaconda/pull/4287 , Anaconda RPMs
are built inside the test VM, not in the container. Just keep libtool
and gobject-introspection-devel, as anaconda needs them for running
`./configure`.
This mostly reverts commit e3afeb4f6a6308c8df1a653b50e116666b08f30b.
-----
This reduces the [compressed container size](https://quay.io/repository/cockpit/tasks?tab=tags) from 777 MB to 723 MB, and the uncompressed size from 2.3 GB to 2.1 GB.
=> Mostly revert "tasks: add anaconda project's build dependencies to container"

.github/workflows/build-images.yml, .github/workflows/build-tasks.yml, images/Dockerfile, tasks/Dockerfile
I built this locally and verified that I can build and test cockpit with chromium and firefox.
=> tasks: Move to Fedora 37, drop container script labels

tasks/Dockerfile
There are required to build the binary package (wheel) for the pybridge scenario.
Required for cockpit-project/cockpit#17922.
=> tasks: add python3-{build,wheel}

ansible/aws/tasks/launch-coreos.yml
`rpm-ostree install` now asks for confirmation, which caused the playbook to hang indefinitely. Add missing `-y` option.
----
I just re-deployed our webhook EC2 instance, mostly to make sure this still works. Can't hurt to refresh it occasionally. And voilà, it didn't..
=> ansible: Fix Python installation

tasks/Dockerfile
This hasn't been used in two years [1], removed from our secrets git repo, and generally does not belong into our infrastructure -- things like code coverage reports should be generated and uploaded through GitHub workflows these days.
[1] https://github.com/osbuild/cockpit-composer/issues/1631
=> tasks: Drop codecov-token link

tasks/README.md
The project name on the new OpenShift cluster is now "cockpit".
----
This is [deployed](http://webhook-cockpit.apps.ocp.cloud.ci.centos.org/inspect-queue), but not being used yet. That is coordinated in TODO bots PR.
=> tasks: Update webhook URL for new CentOS CI OCP

metrics/README.md, metrics/centosci-ci-weather.yaml, metrics/metrics.yaml, metrics/prometheus-claim.yaml
The project name on the new OpenShift cluster is now "cockpit". The
PVC name changed, and the claim now only guarantees 5 GiB.
Add a paragraph about the CI weather to README.
---
I rolled this out to validate our [onboarding request](https://pagure.io/centos-infra/issue/991#comment-831950), and it works. I also copied over our `test-results.db`. Of course the [Grafana board](https://grafana-cockpit.apps.ocp.cloud.ci.centos.org/d/ci/cockpit-ci) is still rather empty, as the prometheus database was reset.
The weather report also works.
Currently, prometheus is not being updated, and the [statistics queue](http://webhook-cockpit.apps.ocp.cloud.ci.centos.org/inspect-queue) is growing. This is because the old CentOS CI cluster cannot talk to the webhook/AMQP queue on the new CentOS CI cluster, …
=> metrics: Move to new CentOS CI OCP

tasks/cockpit-tasks-centosci.yaml
https://github.com/cockpit-project/bots/pull/4162 adjusted run-queue to skip processing tasks queues in environments without /dev/kvm. That is the case on the new CentOS CI cluster. We still need a single task runner to process the statistics queue, as our `test-results.db` can only be written from CentOS CI.
Turn down the resource allocation, this hardly needs any CPU/RAM. Also adjust the persistent volume to re-use our "prometheus-data" PVC, which is where we store our `test-results.db`.
----
I rolled this out, and the tasks instance successfully processed the "statistics" queue backlog (we previously had about 10 items since we moved to the CentOS CI webhook yesterday). 
The last entry in the queue was this:
```json
{"command": "./store-tests --db /cache/images/test-results.db --repo …
```
=> tasks: Adjust CentOS CI tasks runner spec for statistics-only mode

metrics/cockpit-ci.json
Add code coverage by project to cockpit-ci grafana dashboard.
=> cockpit-ci: add code coverage

tasks/cockpit-tasks
Containers sometimes got into a state where each libvirt invocation failed like this:
libvirt: XML-RPC error : Failed to connect socket to '/work/.cache/libvirt/virtqemud-sock':
No such file or directory
This was because we killed virtqemud, but it didn't clean up its state in ~/.cache/libvirt/run. Make sure that this happens.
----
This is a common infra-like failure. Equally importantly, it's time to refresh our tasks container to the current browser versions.
=> tasks: Clean up libvirt files between runs

tasks/Containerfile
In our projects we have used ruff long enough to commit to it. Let's
have it in our development toolboxes by default then, so that we don't
keep sending PRs which break ruff rules.
This also enables our other projects to start using ruff in CI (which
runs in tasks, instead of a dedicated unit-tests container).
=> tasks: Install ruff

ansible/psi/README.md
See https://bugzilla.redhat.com/show_bug.cgi?id=2218141
----
@marusak , @allisonkarlitskaya : This works fine for me (I upped https://bodhi.fedoraproject.org/updates/FEDORA-2023-88df046168). Until it lands, you must grab the version from bodhi, I used 
sudo dnf install https://kojipkgs.fedoraproject.org//packages/ansible-collections-openstack/2.1.0/1.fc38/noarch/ansible-collections-openstack-2.1.0-1.fc38.noarch.rpm
=> ansible: Fix OpenStack setup for Fedora 38

tasks/Containerfile
This is still used by older Cockpit test APIs, for old subscription-manager branches.
---
See https://github.com/cockpit-project/bots/pull/5267
I [rebuilt the container](https://github.com/cockpit-project/cockpituous/actions/runs/6205223414) and rolled it out.
=> tasks: Put back python3-pyyaml

tasks/install-service
In some situations (in particular the fedora-rawhide-boot and -payload images) gain an extra SELinux "Multi-category range" context like this:
system_u:object_r:container_file_t:s0:c220,c230  fedora-rawhide-boot-ba19e37f2b38f6578574275b7eb209e5b1850bceb9eb671cb366db16e4bf78fc.iso
This makes them undeletable by `image-prune`, `rm`, or anything else that the container could do. This causes old images to pile up, and the host eventually fails with ENOSPC.
There is nothing that the container can do to fix these files, and it's not clear what causes this in the first place. To mitigate, reset the context level in the system unit at startup.
----
Our bots have ran into ENOSPC quite frequently, but so far I had always only quick-fixed this by mass-deleting the image cache. This should fix it …
=> tasks: Reset SELinux level of images on startup

tasks/run-local.sh
This validates https://github.com/cockpit-project/bots/pull/5542
----
=> tasks: Check image pruning in run-local.sh

tasks/Containerfile
I locally built this and ran the podman tests successfully.  I'm sure that there will be some fallout wrt. pixel tests and such, I'll go through them.
=> tasks: Move to Fedora 39

tasks/Containerfile
We don't build anaconda-core from sources anymore. We do that for the anaconda-webui only, but this is not needed for it.
Followup for 593d3d18629adc0b0cea17e332a8c5bec6394652.
=> Completely remove Anaconda build dependencies

ansible/psi/deploy-all.sh, ansible/psi/psi_defaults.yml, ansible/roles/launch-openstack-instance/tasks/main.yml
To debug some ongoing network issue, I'm redeploying a few (or soon, all) rhos workers.
=> ansible: Adjust to Openstack SDK 1.0 Ansible API changes, update PSI workers to Fedora 39

tasks/Containerfile
This is equivalent to `podman --remote` and sends commands to a running daemon.  We can use this to communicate with a podman daemon running outside of the container with its socket bind-mounted in.
Also, sort!
=> tasks: add podman-remote

tasks/cockpit-tasks
Commit 93523ff684b15e broke OpenShift deployments: The `export HOME` from `setup-tasks` isn't visible in the main `cockpit-tasks` loop, so the GitHub API fails to resolve the user's home dir.
Put it back for now. This is far from elegant, but we need to unbreak the statistics queue quickly.
----
http://webhook-cockpit.apps.ocp.cloud.ci.centos.org/inspect-queue is building up a lot of pending `statistics` requests, it fails with
```
Traceback (most recent call last):
File "/work/bots/./run-queue", line 36, in <module>
from task import distributed_queue
File "/work/bots/task/__init__.py", line 51, in <module>
api = github.GitHub()
^^^^^^^^^^^^^^^
File "/work/bots/task/github.py", line 157, in __init__
self.log = Logger(self.cache.directory)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> tasks: Fix OpenShift instances

ansible/README.md, ansible/e2e/setup.yml, ansible/inventory/localvm
Add an example inventory for our standard cockpit bots `c` machine. It should be obvious from there how to extend it.
=> ansible: Document how to run a playbook against a local VM

tasks/Containerfile
This seems to be the standard Python asyncio HTTP library. python3-aioresponses is a useful mocking framework for use with pytest.
We're going to be using these soon.
=> tasks: add python3-aiohttp and aioresponses

tasks/README.md, tasks/cockpit-tasks-centosci.yaml, tasks/images-claim-centosci.yaml
This was premature -- we *do* have an OpenShift tasks deployment on CentOS CI, with a single pod that processes the `statistics` queue.
This mostly reverts commit 2ef32979f8c7d8ad1318405c166c4088b603185c. Adjust the documentation to current reality.
----
Spotted while @allisonkarlitskaya and I talked about CI design. This is [very much alive](https://console-openshift-console.apps.ocp.cloud.ci.centos.org/k8s/ns/cockpit/pods).
=> Revert "tasks: Drop CentOS CI OpenShift deployment"

tasks/README.md
Rendered view: https://github.com/cockpit-project/cockpituous/blob/local-doc/tasks/README.md#running-single-container-locally
=> tasks: Document running single container locally in podman

ansible/maintenance/deploy-tasks-container.yml
Our machines have piled up a few dozen GB of old tasks containers. This will keep the current and the new image, and get rid of all older ones.
----
I validated that this works while deploying the new tasks container for https://github.com/cockpit-project/cockpit/pull/20107#issuecomment-1970732087
=> ansible: Clean up old container images in deploy-tasks-container.yml

ansible/roles/tasks-systemd/tasks/main.yml
With current Fedora 39, Chromium often runs into these crashes:
```
AVC avc:  denied  { execheap } for  pid=3725873 comm="ThreadPoolForeg" scontext=system_u:system_r:container_t:s0:c439,c758 tcontext=system_u:system_r:container_t:s0:c439,c758 tclass=process permissive=0
systemd-coredump[3725903]: [Process 3725873 (headless_shell) of user 1111 terminated abnormally without generating a coredump.
```
This causes the browser to hang, and the test force-killed after the timeout.
The general tone in past bug reports is that this is intended -- heap shouldn't be writable and executable at the same time. So Chromium is doing something dubious here.
This isn't something we can easily influence, so just poke a hole into the policy.
This was generated by collecting the full denial with `ausearch -c …
=> ansible: Apply "execheap" SELinux policy hack

.github/workflows/tests.yml, tasks/install-service, tasks/run-local.sh
tasks: Bind the host's podman API socket
This paves the way for spawning per-job tasks containers from the
container (via `job-runner`).
Getting the permissions right is unfortunately annoyingly complicated, as the
host's socket has 660 permissions, but the tasks container runs as uid 1111.
Ideally we could use something like
-v "${XDG_RUNTIME_DIR:-/run}/podman/podman.sock:/podman.sock:idmap=gids=$(id -g)-1111-1"
but that fails with "invalid mappings", and is generally not well documented.
`--mount=type=bind,[...],idmap --uidmap [...]` does not work either.
So resort to file permissions for the host's `podman.sock`:
- For local developers in `run-local.sh`, make the socket world
writable. This does not actually hurt for a human developer: Its
directory (/run/user/uid) is not accessible …
=> tasks: Bind the host's podman API socket

.github/workflows/tests.yml, ansible/roles/webhook/cockpituous-webhook.service, push-container, tasks/Containerfile, tasks/install-service, tasks/run-local.sh
This is a grab-bag of small unrelated stuff. @allisonkarlitskaya I took in and fixed your `$CONTAINER_HOST` change from #586. Can you please test `tasks/run-local.sh` with this? With any luck it fixes it. If not, I'm also happy to add `--security-opt=label=disable` instead like in commit 84e82706bb71bad36e36cd93783a553e79179808
=> Various cleanups

.github/workflows/tests.yml, tasks/mock-github, tasks/run-local.sh
This covers the real thing in between getting the "issue" webhook data
and uploading the image to the S3 server, and hence `issue-scan`,
`image-refresh`, `image-create`, S3 image credentials, etc.
Extend mock-github for the operations that `image-refresh` does, like
converting an issue to a pull, posting test statuses, etc. These aren't
asserted: it's  possible in principle with keeping state in the mock,
but these aren't the parts that are sensitive to us changing our bots
infrastructure. Also, these are better done in bots' unittests than this
integration test.
----
TODO:
=> tasks: Add integration test for image-refresh via issue-scan

.github/workflows/tests.yml, tasks/mock-git-push, tasks/run-local.sh
Broken out of #586 -- these parts apply to the current infra. I re-triggered https://github.com/cockpit-project/bots/pull/6017 and it is green now :green_heart: .
=> run-local.sh: Various cleanups, prepare for job-runner

ansible/roles/tasks-systemd/tasks/main.yml
Tests will need that to download private (RHEL) images from the stores.
For now this is the same directory as the upload secret, but at some point we should split them.
----
This goes along with https://github.com/cockpit-project/bots/pull/6062
I added the secret splitting to the pilot board as enhancement, so that we don't forget.
I did *not* roll this out yet, will do after review.
=> ansible: Define "image-download" job secret

tasks/mock-github, tasks/run-local.sh
Teach `mock-github` to write a log of POST requests, and add some initial assertions. They are not very precise yet (that'll get cleaned up in the Python rewrite soon), but at least ensure that we post the statuses to the expected SHA.
This enables us to create an integration test for a cross-project test in a future commit.
=> tasks: Test posted statuses in mock PR and image refresh

ansible/roles/tasks-systemd/tasks/main.yml
This is necessary for rhel4edge refreshes. Add a new `$COCKPIT_CRC_PASSWORD` env variable for it so that we can stop hardcoding the path in bots rhel4edge.bootstrap.
Also clarify the comments a bit.
---
see https://github.com/cockpit-project/bots/issues/6053
=> ansible: Include console.redhat.com password in image-upload secrets

tasks/run-local.sh
This covers the regression with job-runner for cross-project test
requests: https://github.com/cockpit-project/bots/pull/6045
Due to that revert, this currently tests the old `tests-invoke` code
path. Allow some flexibility in the status description as tests-invoke
and job-runner's descriptions are slightly different.
-----
=> tasks: Test cross-project PR test request

ansible/psi/image-cache.yml, ansible/roles/ci-data-cache/tasks/main.yml, ansible/roles/install-secrets-dir/tasks/main.yml, ansible/roles/tasks-systemd/tasks/main.yml, tasks/install-service
See individual commits for details.
I rolled this out onto rhos-01-1, switched it back to `setenforce 1`, and confirmed that `sudo podman exec -it cockpit-tasks-1 podman-remote --url unix:///podman.sock ps` works and also doesn't leave any "AVC denied" in  `journalctl -f`.
=> Properly fix podman.socket permissions in tasks containers

tasks/install-service
With the run-queue fix [1] landed, we don't need this as indicator for "capable of running tests" any more.
https://github.com/cockpit-project/bots/pull/6080
----
I deployed this already, as it seemed straightforward enough to me. I sent another image trigger to validate: https://github.com/cockpit-project/bots/issues/6081 (it failed for unrelated reasons, but it did pick up the job).
=> tasks: Drop /dev/kvm from cockpit-tasks containers

tasks/container/webhook
This causes a duplicate image-refresh job for auto-generated image refresh issues. These generate both an "opened" and "labelled" event at the same tme, so that we'll get two `issues-scan` webhook queue entries, and the API query in `issue-scan` will see a "bot" labeled issue for both responses.
It is enough to react to the "labeled" event.
=> tasks: Stop reacting to opened issue

tasks/container/cockpit-tasks, tasks/run-local.sh
The `[ -t 0 ]` check in `cockpit-tasks` doesn't do anything any more, as the integration tests now run that script with `podman exec`, without an attached tty. This is also a bit awkward for the upcoming pytest rewrite, so replace it with an environment variable.
=> tasks: Speed up test_pr()

.github/workflows/build-tasks.yml, Makefile, ansible/maintenance/deploy-tasks-container.yml, ansible/roles/webhook/cockpituous-webhook.service, tasks/README.md, tasks/cockpit-tasks-centosci.yaml, tasks/cockpit-tasks-webhook.yaml, tasks/install-service, tasks/mock-github, tasks/run-local.sh
This speeds things up (due to having the runner closer to the registry) and simplifies credentials management: we'll be able to drop our quay.io environment after this.
Move the amd64 and manifest jobs back to GitHub so they can run on GitHub infra, closer to the container registry.
I already did a run of this and it worked nicely.  See https://github.com/cockpit-project/cockpituous/actions/runs/8307247489 and https://github.com/orgs/cockpit-project/packages
I also started to try porting the container-file-updater-script to GitHub's API.  That was fairly straight-forward, but with an important caveat: in its first iteration, it was not possible to use ghcr at all without a GitHub token, even on public repos.  Since then, they've carved out enough of an exception to allow `podman pull` to …
=> workflows: move tasks container to ghcr.io

tasks/build-secrets, tasks/cockpit-tasks-centosci.yaml
Commit b742b2d601c55fd4 was a thinko -- we *do* need S3 upload on our OpenShift tasks container: While we keep `test-results.db` in the local /cache/images/, we push `prometheus-stats` to S3.
----
I deployed this on OpenShift, and ran
```
./store-tests --db /cache/images/test-results.db --repo cockpit-project/cockpit-podman 84a41aa41a3abb587a44e1c44aa7615133a3bef8 && ./prometheus-stats --db /cache/images/test-results.db --s3 https://cockpit-logs.us-east-1.linodeobjects.com/prometheus
```
in the terminal. This works now. I'm afraid it's too much manual effort to try and rescue the recently landed PRs, so we'll effectively rebuild the statistics from scratch now.
=> tasks: Give S3 secrets to OpenShift tasks container

ansible/maintenance/sync-secrets.yml, ansible/psi/image-cache.yml, ansible/roles/local-s3-alias/tasks/main.yml
The psi/image-cache playbook installs the s3-keys/ symlink for the local S3 mirror on rhos-01-1. But sync-secrets clobbers that (as it always removes the entire existing secrets dir before re-syncing it).
Fix this by factoring out the symlink creation into a nwe "local-s3-alias" role and calling it from both places.
----
I tested this by first removing the existing symlink /var/lib/cockpit-secrets/tasks/s3-keys/10.0.203.194, then running
```
ansible-playbook -v -i inventory psi/image-cache.yml
```
which installed it everywhere. Afterwards I ran
```
ansible-playbook -v -i inventory maintenance/sync-secrets.yml  -l rhos-01-1
```
(i.e. the step which previously removed the symlink), and confirmed that it installed it correctly. In a tasks container I can now do
```
$ ./image-upload --store …
```
=> ansible: Fix sync-secrets playbook to not clobber s3-keys alias symlinks

tasks/container/Containerfile
This is a prerequisite for proper mypy testing of the upcoming pytest in PR #606
=> tasks: Install types-PyYAML into container

ansible/roles/tasks-systemd/tasks/main.yml
Commit dbd7643e5c958 caused a regression: The `cafile` npmrc option *only* uses the given CA, while `$NODE_EXTRA_CA_CERTS` uses the given CA *in addition*. That broke fetching npm modules directly from github.com, which needs the system default CA lists.
---
Blocks https://github.com/cockpit-project/bots/pull/6148 and also https://github.com/cockpit-project/bots/pull/6160. See the former for debugging notes.
=> ansible: Move npm CA file back to env variable

ansible/roles/tasks-systemd/tasks/main.yml
Define a `cockpituous-git-cache` persistent volume so that the expensive and big node-cache.git (plus the much less expensive bots.git) get re-used between jobs.
Note that we don't want to keep *all* of `$XDG_CACHE_HOME`, in particular not the libvirt/ directory. So restrict that to the
`cockpit-dev/` subdirectory, which is handled by cockpit's `git-utils.sh`.
Fixes #611
----
I applied this to rhos-01-1, started a local test [log](https://cockpit-logs.us-east-1.linodeobjects.com/cockpit-podman-cache-test-2/log.html), and inspected the resulting volume from the outside:
```
$ sudo ls -l /var/lib/containers/storage/volumes/cockpituous-git-cache/_data/cockpit-project
total 0
drwxr-xr-x. 1 cockpituous cockpituous 62 Apr  6 08:57 bots.git
drwxr-xr-x. 1 cockpituous cockpituous 62 Apr  6 08:57 …
```
=> ansible: Configure persistent git cache volume for job containers

ansible/roles/local-s3-alias/tasks/main.yml, ansible/roles/local-secrets-archive/tasks/main.yml, ansible/roles/tasks-systemd/tasks/main.yml, local-s3/install-s3-service, tasks/README.md, tasks/build-secrets, tasks/install-service, test/test_deployment.py
Subdirectories in secrets are awkward with kubernetes secrets. It's also desirable to hand out access to them in a finer-grained manner.
Our ci-secrets.git repo already moved the S3 keys out of tasks/ into the top level. Follow suit.
---
This has been on the "cleanup" list for some time, and will also enable us to consistently move to kubernetes secrets for all deployments. Doing this step separately as it's quite intrusive.
=> Move S3 keys secrets out of tasks secrets

ansible/roles/local-secrets-archive/tasks/main.yml, local-s3/install-s3-service, tasks/build-secrets, test/test_deployment.py
Tasks containers don't need, and therefore should not have, the local minio S3 server certificate.
Our ci-secrets.git repo already moved the S3 certificate out of `tasks/` into the top level `s3-server/` directory. Adjust the deployment scripts and integration test accordingly.
=> Split s3 server certificate out of tasks secrets

tasks/container/Containerfile
This is required for talking to Chromium through the webdriver (classic and BiDi) protocol. Getting this from the distribution ensures a matching version to chromium-headless.
---
See https://github.com/cockpit-project/starter-kit/pull/934 . This is at most 13 MB of dead weight, but it enables projects to talk webdriver/bidi directly, or use e.g. [webdriver from npm](https://www.npmjs.com/package/webdriver)
=> tasks: Install chromedriver

tasks/container/Containerfile
This is required by anaconda tests as they are using `mkksiso` to adjust the test ISO file. [1]
[1]: https://github.com/rhinstaller/anaconda-webui/pull/462
=> tasks: Install lorax

pyproject.toml, tasks/README.md
These days we have to explicitly set `$COCKPIT_IMAGES_DATA_DIR`.
Drop the explicit "bash" command, it's not necessary any more.
=> tasks: Fix image cache in local podman container, fix ruff 0.7 errors

.github/workflows/build-tasks.yml
We tend to forget about refreshing the tasks container, and thus fall
behind on browser and toolchain updates.
Run these every Saturday, so that they are ready for the Sunday night
runs of our projects' tasks-container-update workflows.
=> workflows: Auto-refresh tasks container every week

ansible/aws/README.md, ansible/roles/tasks-systemd/cockpituous-janitor.service, ansible/roles/tasks-systemd/cockpituous-janitor.timer, ansible/roles/tasks-systemd/tasks/main.yml, tasks/install-service
Our bots accumulate outdated task containers which eat a lot of space over time. This will become worse now with automated tasks updates from commit 482418852d.
Our machinery also sometimes leaks exited/failed containers, clean them up as well.
----
Our bot instances tend to look like this:
```
$ sudo podman ps -a
CONTAINER ID  IMAGE                                     COMMAND               CREATED       STATUS                   PORTS       NAMES
94a5d1418d0e  ghcr.io/cockpit-project/tasks:2024-10-07  python3 -c #!/usr...  11 days ago   Exited (1) 11 days ago               serene_lewin
c4aa8e31eaeb  ghcr.io/cockpit-project/tasks:2024-10-07  python3 -c #!/usr...  31 hours ago  Exited (2) 31 hours ago              funny_solomon
fb7bad7a6718  ghcr.io/cockpit-project/tasks:2024-10-07  python3 …
```
=> tasks: Regularly clean up leftover containers and outdated images

ansible/roles/tasks-systemd/tasks/main.yml
On Fedora CoreOS, SELinux wants the socket path in /run, while on Fedora
40 (on our PSI runners) it wants to go via /var/run, due to the
conflicting "extra_varrun" custom policy that Fedora installs for
migration.
Adjust the policy for /run (see [1] and bump priority to avoid
conflicting with extra_varrun.
[1] https://discussion.fedoraproject.org/t/f40-change-proposal-move-var-run-selinux-policy-entries-to-run-self-contained/100171
---
See https://github.com/orgs/cockpit-project/projects/4/?pane=issue&itemId=69115598 . Tested on PSI and AWS.
=> ansible: Fix podman socket SELinux context on AWS

tasks/container/Containerfile
Our tests need it, but it doesn't get installed as transient recommends any more.
---
The [12-07 tasks container refresh](https://github.com/cockpit-project/cockpituous/pkgs/container/tasks) lost this package, so that at least bots tests now fail:
```
❱❱ pytest -vv
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov-config=pyproject.toml
inifile: /var/home/martin/upstream/bots/pyproject.toml
rootdir: /var/home/martin/upstream/bots
```
Which can also be seen [in this failure](https://github.com/cockpit-project/bots/actions/runs/12218266517/job/34083524776?pr=7196) of https://github.com/cockpit-project/bots/pull/7196 which ran against  2024-12-07.
I [triggered a build](https://github.com/cockpit-project/cockpituous/actions/runs/122182 …
=> tasks: Explicitly install python3-pytest-cov

.github/workflows/build-tasks.yml, .github/workflows/tests.yml, tasks/credentials/openssl.cnf
This gets rid of the podman backport PPA, and thus finally runs the integration test on the *exact* same machinery as the production build (which previously has led to problems like in #628).
We can now also stop repeating the test dependencies.
=> workflows: Move to Ubuntu 24.04

tasks/container/Containerfile
Project updates to this container (worked, but not landing until this is approved):
These need some more fixes:
=> tasks: Move to Fedora 41

metrics/metrics.yaml, tasks/cockpit-tasks-webhook.yaml
Some fallout from my CI wrestling today (for OpenSSL 3 certs, this was unrelated Yak shaving).
=> tasks: Delay webhook startup; metrics: Adjust config to Prometheus 3

tasks/cockpit-tasks-webhook.yaml, tasks/container/webhook
Commit 06c2717be74 introduced a retry loop for connecting to AMQP, as
these two containers start at the same time in the OpenShift deployment.
However, these days the webhook often fails with `ssl.SSLEOFError`
(with parents `SSLError` and `OSError`), which doesn't fit `AMQPError`.
So intercept this as well.
With that we can revert the static sleep from commit 169b53bac1998
again.
Fixes #635
----
=> webhook: Retry OSError on queue connection failure

tasks/container/Containerfile
The headless version has several bugs, at least [1] and [2]. Also, headless and full Chromium render texts slightly differently, so we can't debug/fix pixel tests with `TEST_SHOW_BROWSER=pixels`.
This is a net 100 MB size increase of the tasks container, and will break all pixel tests once, but long-term it is a better browser.
[1] https://issues.redhat.com/browse/COCKPIT-1159
[2] https://github.com/cockpit-project/cockpit-files/pull/911#issuecomment-2602064380
=> tasks: Install full chromium

tasks/container/Containerfile
This is recommened package for wikitcms needed for authentication to fedora wiki but because we `--setopt=install_weak_deps=False` this was not installed.
=> Add weak dependency of wikitcms needed by anaconda-webui infra

ansible/roles/tasks-systemd/tasks/main.yml
For posting Anaconda nightly compose test results to the Fedora Wiki staging instance.
=> ansible: Add fedora-wiki-staging tasks secret

ansible/psi/README.md
Commit 583a802b1c505cd was wrong: While "Red Hat Employment SSO" works for general administration, it does not work for creating user application credentials.
=> psi: Fix OpenStack web ui login documentation

tasks/mock-github
Since githubusercontent is now rate limited bots changed to obtaining the .cockpit-ci/container file from the GitHub rest API.
=> mock-github: adjust .cockpit-ci/container location

.github/workflows/cleanup-tasks.yml
We've accrued tons of outdated and unsupported tasks images, plus the tasks-tmp intermediate one. Clean up our registry regularly using [1].
Use our new `used-tasks-tags` script [2] to determine which tags are currently in use. Also keep the most recent six tags, in case we need to investigate some flakes.
Start with dry-mode, to establish the workflow on main and allow us to run it manually from a branch.
[1] https://github.com/marketplace/actions/ghcr-io-cleanup-action
[2] https://github.com/cockpit-project/bots/pull/7944
----
I did a [first run](https://github.com/cockpit-project/cockpituous/actions/runs/16068048767/job/45346272265) with attaching this to the existing "build-tasks" workflow, as we can't run a workflow from a branch that doesn't exist on main. Its output looks very …
=> workflows: Clean up unused tasks containers (dry mode)

README.md, ansible/roles/tasks-systemd/tasks/main.yml, logs-proxy/README.md, logs-proxy/proxy.yaml, logs-proxy/s3-proxy.py, tasks/build-secrets, test/test_deployment.py
We will make our S3 logs bucket private, and only allow reading logs through an Anubis proxy. This hopefully resolves the ridiculous traffic that we've been getting on our S3 buckets due to AI scrapers.
https://issues.redhat.com/browse/COCKPIT-1288.
See individual commits for details.
I deployed this. For testing I made a [single file private](https://cockpit-logs.us-east-1.linodeobjects.com/pull-2175-60c819be-20250703-052724-arch/log) (you'll get AccessDenied), but it's accessible through the proxy: https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-2175-60c819be-20250703-052724-arch/log
=> Anubis proxy for our cockpit-logs S3 bucket

.github/workflows/build-tasks.yml
Commit a4c513ac49 moved the workflow to checkout@v5. The buildjet runners don't get along with this, apparently they don't have a new enough nodejs installed yet:
> Error: System.ArgumentOutOfRangeException:
> Specified argument was out of the range of valid values.
> (Parameter ''using: node24' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')
Move to a GitHub ARM runner instead.
=> workflows: Build ARM tasks image on GitHub runner

ansible/roles/tasks-systemd/tasks/main.yml, test/test_deployment.py
We're about to change the default of this to `false` to enable more of the job-runner internals to be used from other scripts.
=> ansible: set `post = true` in job-runner.toml
